import { describe, expect, it, beforeAll } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * End-to-end test of the Figma plugin's sandbox half, against the BUILT bundle.
 *
 * This replaces a browser page that had to be opened by hand and whose only
 * assertion was that one node had been inserted. That page passed for weeks
 * while the plugin dropped the traced copy on top of the original for every
 * layer inside a frame, because it never read where the copy went — and its
 * fake node had no parent, so it could not have represented a nested layer even
 * if it had. Manual verification that asks "did it run" is why this shipped.
 *
 * `dist/code.js` is the sandbox half, which by design touches no DOM — only the
 * `figma` global. That makes it runnable under Node with the global stubbed,
 * so the check runs in CI on every commit instead of when somebody remembers.
 *
 * It asserts against the built artefact rather than the TypeScript on purpose:
 * the bug that motivated this was invisible in source review and only showed up
 * in behaviour.
 */

const DIST = join(__dirname, '..', 'extensions', 'figma', 'dist', 'code.js');

interface FakeNode {
  id: string;
  type: string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  parent: FakeFrame | null;
  absoluteBoundingBox: { x: number; y: number; width: number; height: number } | null;
  resize(w: number, h: number): void;
  exportAsync(): Promise<Uint8Array>;
}
interface FakeFrame extends FakeNode {
  layoutMode: string;
  appendChild(child: FakeNode): void;
}

let handler: (msg: unknown) => Promise<void>;
let registry: Map<string, FakeNode>;
let selection: FakeNode[];
let inserted: string[];
let notices: { msg: string; error: boolean }[];
let nextId = 1;

function node(over: Partial<FakeNode> = {}): FakeNode {
  const n = {
    id: `n${nextId++}`,
    type: 'RECTANGLE',
    name: 'Logo',
    x: 10, y: 20, width: 200, height: 200,
    parent: null,
    absoluteBoundingBox: null,
    resize(this: FakeNode, w: number, h: number) { this.width = w; this.height = h; },
    exportAsync: async () => new Uint8Array([137, 80, 78, 71]),
    ...over,
  } as FakeNode;
  if (!n.absoluteBoundingBox) {
    // The way Figma composes it: the node's own offset plus every ancestor's.
    let ax = n.x, ay = n.y, p: FakeFrame | null = n.parent;
    while (p) { ax += p.x; ay += p.y; p = p.parent; }
    n.absoluteBoundingBox = { x: ax, y: ay, width: n.width, height: n.height };
  }
  registry.set(n.id, n);
  return n;
}

function frame(over: Partial<FakeFrame> = {}): FakeFrame {
  const f = node({ type: 'FRAME', name: 'Frame', layoutMode: 'NONE', ...over } as Partial<FakeNode>) as FakeFrame;
  f.appendChild = (child: FakeNode) => { child.parent = f; };
  return f;
}

/** Valid output, including the XML comment `trace()` actually prepends. */
const SVG = '<!-- Generated by vecline --><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><path d="M0 0h10v10H0z" fill="#123"/></svg>';

/** One full ready -> traced round trip; returns the inserted node. */
async function cycle(source: FakeNode): Promise<FakeNode> {
  selection = [source];
  inserted.length = 0;
  await handler({ type: 'ready' });
  await handler({ type: 'traced', svg: SVG, sourceId: source.id, ssim: 0.98, psnr: 33.8, ms: 428, bytes: 4227 });
  return selection[0];
}

beforeAll(async () => {
  if (!existsSync(DIST)) throw new Error(`build the plugin first: ${DIST} is missing`);

  registry = new Map();
  selection = [];
  inserted = [];
  notices = [];

  (globalThis as Record<string, unknown>)['__html__'] = '<html></html>';
  (globalThis as Record<string, unknown>)['figma'] = {
    showUI: () => {},
    ui: {
      postMessage: () => {},
      set onmessage(fn: (msg: unknown) => Promise<void>) { handler = fn; },
      get onmessage() { return handler; },
    },
    currentPage: {
      get selection() { return selection; },
      set selection(v: FakeNode[]) { selection = v; },
    },
    viewport: { scrollAndZoomIntoView: () => {} },
    notify: (msg: string, opts?: { error?: boolean }) => { notices.push({ msg, error: !!opts?.error }); },
    // Real Figma parses XML, which tolerates a leading comment. A fake that
    // demanded the string start with `<svg` would be stricter than production
    // and would raise a false alarm rather than a real one.
    createNodeFromSvg: (svg: string) => {
      if (!/^\s*(<!--[\s\S]*?-->\s*)*<svg/.test(svg)) throw new Error('not an svg');
      inserted.push(svg);
      return node({ name: 'inserted', x: 0, y: 0, width: 400, height: 400 });
    },
    getNodeByIdAsync: async (id: string) => registry.get(id) ?? null,
    on: () => {},
  };

  await import(/* @vite-ignore */ DIST);
  if (typeof handler !== 'function') throw new Error('code.js did not register a ui.onmessage handler');
});

describe('figma plugin sandbox', () => {
  it('places the copy beside a top-level layer and names it after the source', async () => {
    const out = await cycle(node({ x: 10, y: 20 }));
    expect(inserted).toHaveLength(1);
    expect(out.x).toBe(10 + 200 + 40);
    expect(out.y).toBe(20);
    expect([out.width, out.height]).toEqual([200, 200]);
    expect(out.name).toBe('Logo (vecline)');
  });

  it('does not stack coordinate spaces for a layer nested in a frame', async () => {
    // The regression. Source at (25,30) inside a frame at (300,50). The old code
    // put the copy at x = 265 on the page: 60px left of the frame origin, on top
    // of the original, and painting above it as the page's last child.
    const f = frame({ x: 300, y: 50, width: 800, height: 600 });
    const nested = node({ x: 25, y: 30, parent: f });
    const out = await cycle(nested);

    expect(out.parent).toBe(f);
    expect(out.x).toBe(25 + 200 + 40);
    expect(out.y).toBe(30);
    expect(out.x).toBeGreaterThanOrEqual(nested.x + nested.width);
  });

  it('stays on the page with absolute coordinates under auto-layout', async () => {
    // Adopting the copy here would let the parent immediately reflow it.
    const auto = frame({ x: 300, y: 50, layoutMode: 'VERTICAL' });
    const inAuto = node({ x: 25, y: 30, parent: auto });
    const out = await cycle(inAuto);

    expect(out.parent).not.toBe(auto);
    expect(out.x).toBe(325 + 200 + 40);
    expect(out.y).toBe(80);
  });

  it('binds the result to the traced layer, not to whatever is selected later', async () => {
    const traced = node({ name: 'Original', x: 0, y: 0, width: 120, height: 90 });
    const other = node({ name: 'Something else', x: 900, y: 900, width: 40, height: 40 });

    selection = [traced];
    inserted.length = 0;
    await handler({ type: 'ready' });
    selection = [other];                                   // the user clicks away
    await handler({ type: 'traced', svg: SVG, sourceId: traced.id, ssim: 0.98, psnr: 33.8, ms: 1, bytes: 1 });

    const out = selection[0];
    expect([out.width, out.height]).toEqual([120, 90]);
    expect(out.name).toBe('Original (vecline)');
  });

  it('reports failures rather than crashing, and inserts nothing for junk', async () => {
    notices.length = 0;
    await handler({ type: 'failed', message: 'decode failed' });
    expect(notices.at(-1)?.error).toBe(true);

    const before = inserted.length;
    notices.length = 0;
    await handler({ type: 'traced', svg: 'not svg at all', sourceId: 'nope', ssim: null, psnr: null, ms: 1, bytes: 3 });
    expect(inserted).toHaveLength(before);
    expect(notices.at(-1)?.error).toBe(true);
  });
});
