import { describe, expect, it } from 'vitest';
import sharp from 'sharp';
import { decodeRaster } from '../src/io/decode.js';
import { compareImages } from '../src/metrics/index.js';
import { decodeBmp, decodePnm, decodeTga, isBmp, isIco, isPnm, isTga, listIcoEntries } from '../src/io/formats/index.js';
import type { RasterImage } from '../src/types.js';
import { createImage, setPixel } from './fixtures.js';

/**
 * Formats libvips is not built with, decoded in pure TypeScript.
 *
 * Every case here builds the container by hand and asserts a **bit-exact**
 * decode, because these are all lossless formats: anything less than exact
 * means a byte-order, padding or scan-direction bug. Odd dimensions are used
 * throughout so row padding is always exercised.
 */

const W = 17;
const H = 11;

function reference(): RasterImage {
  const img = createImage(W, H);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      setPixel(img, x, y, (x * 15) % 256, (y * 23) % 256, ((x + y) * 9) % 256, 255);
    }
  }
  return img;
}

const REF = reference();

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------

function buildBmp(bpp: 24 | 32, topDown = false): Buffer {
  const rowSize = Math.ceil((W * bpp) / 32) * 4;
  const pixels = rowSize * H;
  const offset = 54;
  const b = Buffer.alloc(offset + pixels);

  b.write('BM', 0);
  b.writeUInt32LE(offset + pixels, 2);
  b.writeUInt32LE(offset, 10);
  b.writeUInt32LE(40, 14);
  b.writeInt32LE(W, 18);
  b.writeInt32LE(topDown ? -H : H, 22);
  b.writeUInt16LE(1, 26);
  b.writeUInt16LE(bpp, 28);
  b.writeUInt32LE(pixels, 34);

  for (let row = 0; row < H; row++) {
    const srcY = topDown ? row : H - 1 - row;
    for (let x = 0; x < W; x++) {
      const s = (srcY * W + x) * 4;
      const o = offset + row * rowSize + x * (bpp / 8);
      b[o] = REF.data[s + 2];
      b[o + 1] = REF.data[s + 1];
      b[o + 2] = REF.data[s];
      if (bpp === 32) b[o + 3] = 255;
    }
  }
  return b;
}

/** 8-bit palettised BMP; the palette holds every colour the fixture uses. */
function buildIndexedBmp(): { bytes: Buffer; expected: RasterImage } {
  const colors: number[] = [];
  const index = new Map<number, number>();
  const expected = createImage(W, H);

  for (let i = 0; i < W * H; i++) {
    const key = (REF.data[i * 4] << 16) | (REF.data[i * 4 + 1] << 8) | REF.data[i * 4 + 2];
    if (!index.has(key) && index.size < 256) {
      index.set(key, colors.length);
      colors.push(key);
    }
  }

  const paletteCount = colors.length;
  const rowSize = Math.ceil(W / 4) * 4;
  const offset = 54 + paletteCount * 4;
  const b = Buffer.alloc(offset + rowSize * H);

  b.write('BM', 0);
  b.writeUInt32LE(b.length, 2);
  b.writeUInt32LE(offset, 10);
  b.writeUInt32LE(40, 14);
  b.writeInt32LE(W, 18);
  b.writeInt32LE(H, 22);
  b.writeUInt16LE(1, 26);
  b.writeUInt16LE(8, 28);
  b.writeUInt32LE(paletteCount, 46);

  colors.forEach((key, i) => {
    const o = 54 + i * 4;
    b[o] = key & 0xff;             // stored BGRA
    b[o + 1] = (key >> 8) & 0xff;
    b[o + 2] = (key >> 16) & 0xff;
  });

  for (let row = 0; row < H; row++) {
    const srcY = H - 1 - row;
    for (let x = 0; x < W; x++) {
      const s = (srcY * W + x) * 4;
      const key = (REF.data[s] << 16) | (REF.data[s + 1] << 8) | REF.data[s + 2];
      const idx = index.get(key)!;
      b[offset + row * rowSize + x] = idx;
      const c = colors[idx];
      setPixel(expected, x, srcY, (c >> 16) & 0xff, (c >> 8) & 0xff, c & 0xff, 255);
    }
  }
  return { bytes: b, expected };
}

function buildPnm(magic: 'P6' | 'P5' | 'P3', withComment = true): { bytes: Buffer; expected: RasterImage } {
  const comment = withComment ? '# generated by the test suite\n' : '';
  const expected = createImage(W, H);

  if (magic === 'P3') {
    let body = '';
    for (let i = 0; i < W * H; i++) {
      const r = REF.data[i * 4], g = REF.data[i * 4 + 1], bl = REF.data[i * 4 + 2];
      body += `${r} ${g} ${bl}\n`;
      setPixel(expected, i % W, Math.floor(i / W), r, g, bl, 255);
    }
    return { bytes: Buffer.from(`P3\n${comment}${W} ${H}\n255\n${body}`, 'ascii'), expected };
  }

  const channels = magic === 'P6' ? 3 : 1;
  const px = Buffer.alloc(W * H * channels);
  for (let i = 0; i < W * H; i++) {
    if (channels === 3) {
      px[i * 3] = REF.data[i * 4];
      px[i * 3 + 1] = REF.data[i * 4 + 1];
      px[i * 3 + 2] = REF.data[i * 4 + 2];
      setPixel(expected, i % W, Math.floor(i / W), REF.data[i * 4], REF.data[i * 4 + 1], REF.data[i * 4 + 2], 255);
    } else {
      const v = REF.data[i * 4];
      px[i] = v;
      setPixel(expected, i % W, Math.floor(i / W), v, v, v, 255);
    }
  }
  const head = Buffer.from(`${magic}\n${comment}${W} ${H}\n255\n`, 'ascii');
  return { bytes: Buffer.concat([head, px]), expected };
}

function buildTga(opts: { rle?: boolean; topDown?: boolean; depth?: 24 | 32 } = {}): Buffer {
  const { rle = false, topDown = true, depth = 32 } = opts;
  const bpp = depth / 8;
  const body: number[] = [];

  const pixelAt = (i: number): number[] => {
    const srcY = topDown ? Math.floor(i / W) : H - 1 - Math.floor(i / W);
    const s = (srcY * W + (i % W)) * 4;
    const px = [REF.data[s + 2], REF.data[s + 1], REF.data[s]];
    if (depth === 32) px.push(255);
    return px;
  };

  if (rle) {
    // Emit every pixel as its own one-pixel raw packet; correctness of the
    // packet loop is what matters here, not compression ratio.
    for (let i = 0; i < W * H; i++) body.push(0x00, ...pixelAt(i));
  } else {
    for (let i = 0; i < W * H; i++) body.push(...pixelAt(i));
  }

  const b = Buffer.alloc(18 + body.length);
  b[2] = rle ? 10 : 2;
  b.writeUInt16LE(W, 12);
  b.writeUInt16LE(H, 14);
  b[16] = depth;
  b[17] = topDown ? 0x20 : 0x00;
  Buffer.from(body).copy(b, 18);
  return b;
}

async function buildIco(): Promise<Buffer> {
  const png = await sharp(Buffer.from(REF.data.buffer, REF.data.byteOffset, REF.data.byteLength), {
    raw: { width: W, height: H, channels: 4 },
  }).png().toBuffer();

  const b = Buffer.alloc(6 + 16 + png.length);
  b.writeUInt16LE(0, 0);
  b.writeUInt16LE(1, 2);
  b.writeUInt16LE(1, 4);
  b[6] = W;
  b[7] = H;
  b.writeUInt16LE(1, 10);
  b.writeUInt16LE(32, 12);
  b.writeUInt32LE(png.length, 14);
  b.writeUInt32LE(22, 18);
  png.copy(b, 22);
  return b;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('signature detection', () => {
  it('identifies each container', () => {
    expect(isBmp(buildBmp(24))).toBe(true);
    expect(isPnm(buildPnm('P6').bytes)).toBe(true);
    expect(isTga(buildTga())).toBe(true);
  });

  it('does not claim files belonging to other formats', () => {
    const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13]);
    expect(isBmp(png)).toBe(false);
    expect(isPnm(png)).toBe(false);
    expect(isIco(png)).toBe(false);
    expect(isTga(png)).toBe(false);
  });

  it('rejects empty and truncated input', () => {
    for (const buf of [Buffer.alloc(0), Buffer.from('BM'), Buffer.from('P')]) {
      expect(isBmp(buf)).toBe(false);
      expect(isPnm(buf)).toBe(false);
      expect(isTga(buf)).toBe(false);
      expect(isIco(buf)).toBe(false);
    }
  });
});

describe('BMP', () => {
  it.each([[24], [32]] as const)('decodes %ibpp bottom-up exactly', async (bpp) => {
    const { image } = await decodeRaster(buildBmp(bpp));
    expect(compareImages(REF, image).lossless).toBe(true);
  });

  it('honours a negative height as top-down', async () => {
    const { image } = await decodeRaster(buildBmp(24, true));
    expect(compareImages(REF, image).lossless).toBe(true);
  });

  it('decodes an 8-bit palettised image exactly', async () => {
    const { bytes, expected } = buildIndexedBmp();
    const { image } = await decodeRaster(bytes);
    expect(compareImages(expected, image).lossless).toBe(true);
  });

  /**
   * In 32-bit BI_RGB the fourth byte is officially unused, and many encoders
   * leave it at zero. Honouring that literally would make the whole image
   * transparent, so an all-zero alpha channel is treated as opaque.
   */
  it('treats an all-zero alpha channel as opaque', () => {
    const bytes = buildBmp(32);
    const rowSize = Math.ceil((W * 32) / 32) * 4;
    for (let row = 0; row < H; row++) {
      for (let x = 0; x < W; x++) bytes[54 + row * rowSize + x * 4 + 3] = 0;
    }
    const { image } = decodeBmp(bytes);
    expect(image.data[3]).toBe(255);
  });

  it('reports the source format rather than the payload format', async () => {
    const { meta } = await decodeRaster(buildBmp(24));
    expect(meta.format).toBe('bmp');
    expect([meta.width, meta.height]).toEqual([W, H]);
  });

  it('refuses implausible dimensions instead of allocating', () => {
    const b = Buffer.alloc(54);
    b.write('BM', 0);
    b.writeUInt32LE(54, 10);
    b.writeUInt32LE(40, 14);
    b.writeInt32LE(99_999_999, 18);
    b.writeInt32LE(99_999_999, 22);
    b.writeUInt16LE(24, 28);
    expect(() => decodeBmp(b)).toThrow(/Implausible/);
  });
});

describe('Netpbm', () => {
  it.each(['P6', 'P5', 'P3'] as const)('decodes %s exactly', async (magic) => {
    const { bytes, expected } = buildPnm(magic);
    const { image } = await decodeRaster(bytes);
    expect(compareImages(expected, image).lossless).toBe(true);
  });

  it('skips comments wherever they appear', () => {
    const withComment = decodePnm(buildPnm('P6', true).bytes);
    const without = decodePnm(buildPnm('P6', false).bytes);
    expect(compareImages(withComment.image, without.image).lossless).toBe(true);
  });

  it('inverts PBM, where a set bit means black', () => {
    const bytes = Buffer.concat([Buffer.from('P4\n8 1\n', 'ascii'), Buffer.from([0b10000000])]);
    const { image } = decodePnm(bytes);
    expect(Array.from(image.data.slice(0, 4))).toEqual([0, 0, 0, 255]);       // bit set
    expect(Array.from(image.data.slice(4, 8))).toEqual([255, 255, 255, 255]); // bit clear
  });

  it('rejects a malformed header', () => {
    expect(() => decodePnm(Buffer.from('P6\nnot-a-number\n', 'ascii'))).toThrow(/Malformed/);
  });
});

describe('TGA', () => {
  it.each([
    ['32-bit top-down', { depth: 32, topDown: true }],
    ['24-bit top-down', { depth: 24, topDown: true }],
    ['32-bit bottom-up', { depth: 32, topDown: false }],
    ['run-length encoded', { depth: 32, topDown: true, rle: true }],
  ] as const)('decodes %s exactly', async (_name, opts) => {
    const { image } = await decodeRaster(buildTga(opts as never));
    expect(compareImages(REF, image).lossless).toBe(true);
  });

  it('reads the dimensions back', () => {
    const { image } = decodeTga(buildTga());
    expect([image.width, image.height]).toEqual([W, H]);
  });
});

describe('ICO', () => {
  it('decodes a PNG-payload icon exactly', async () => {
    const { image, meta } = await decodeRaster(await buildIco());
    expect(meta.format).toBe('ico');
    expect(compareImages(REF, image).lossless).toBe(true);
  });

  it('lists its entries', async () => {
    const entries = listIcoEntries(await buildIco());
    expect(entries).toHaveLength(1);
    expect(entries[0].isPng).toBe(true);
    expect([entries[0].width, entries[0].height]).toEqual([W, H]);
  });

  it('reads a stored dimension of zero as 256', () => {
    const b = Buffer.alloc(6 + 16 + 8);
    b.writeUInt16LE(1, 2);
    b.writeUInt16LE(1, 4);
    b[6] = 0; // means 256
    b[7] = 0;
    b.writeUInt32LE(8, 14);
    b.writeUInt32LE(22, 18);
    expect(listIcoEntries(b)[0].width).toBe(256);
  });
});

describe('unsupported input', () => {
  it('names the formats it does support', async () => {
    await expect(decodeRaster(Buffer.from('definitely not an image at all', 'ascii')))
      .rejects.toThrow(/PNG, JPEG, WebP, AVIF, TIFF, GIF, BMP, ICO/);
  });
});

describe('TGA alpha follows the header, not the bytes', () => {
  /**
   * Bits 0-3 of the image descriptor are the ALPHA BIT COUNT. Zero means the file
   * carries no alpha channel, so the fourth byte of a 32-bit pixel is undefined
   * padding. This decoder read it anyway, and plenty of writers leave it as
   * scratch precisely because the header says not to.
   *
   * Measured on real files from the format-authority corpora: a colour-mapped RLE
   * TGA with attributeBits 0 decoded with 0 of 16,384 pixels opaque — the entire
   * image invisible, which is why pixel mode emitted an SVG with no shapes and
   * still called it bit-exact. A 32-bit RLE file came back 1 of 39,601 opaque.
   */
  function tga32(alphaByte: (i: number) => number, attributeBits: number): Buffer {
    const w = 4, h = 4;
    const body: number[] = [];
    for (let i = 0; i < w * h; i++) body.push(20, 90, 200, alphaByte(i));
    const b = Buffer.alloc(18 + body.length);
    b[2] = 2;                       // uncompressed true-colour
    b.writeUInt16LE(w, 12);
    b.writeUInt16LE(h, 14);
    b[16] = 32;
    b[17] = 0x20 | (attributeBits & 0x0f);  // top-down, plus the alpha-bit count
    Buffer.from(body).copy(b, 18);
    return b;
  }

  const alphaOf = (img: RasterImage): number[] => {
    const out: number[] = [];
    for (let i = 3; i < img.data.length; i += 4) out.push(img.data[i]);
    return out;
  };

  it('ignores the alpha byte when the header declares no alpha channel', () => {
    // Garbage in the padding byte, and the header says it is padding.
    const { image: img } = decodeTga(tga32((i) => i * 7, 0));
    expect(alphaOf(img).every((a) => a === 255), 'a file with no alpha channel decoded translucent').toBe(true);
  });

  it('honours real alpha when the header declares 8 bits', () => {
    const { image: img } = decodeTga(tga32((i) => (i < 8 ? 0 : 255), 8));
    const alpha = alphaOf(img);
    expect(alpha.filter((a) => a === 0).length).toBe(8);
    expect(alpha.filter((a) => a === 255).length).toBe(8);
  });

  it('treats a declared-but-entirely-zero alpha channel as unused', () => {
    // A writer can say "8 alpha bits" and leave every byte at 0. Taking that
    // literally yields a wholly invisible image; stb_image and libtga apply the
    // same heuristic. Two files in the corpora do exactly this.
    const { image: img } = decodeTga(tga32(() => 0, 8));
    expect(alphaOf(img).every((a) => a === 255)).toBe(true);
  });

  it('does not touch a genuinely transparent region inside a real RGBA image', () => {
    // The heuristic is all-or-nothing on purpose: one non-zero alpha anywhere
    // means the channel is in use and every value stands.
    const { image: img } = decodeTga(tga32((i) => (i === 0 ? 255 : 0), 8));
    const alpha = alphaOf(img);
    expect(alpha[0]).toBe(255);
    expect(alpha.slice(1).every((a) => a === 0)).toBe(true);
  });
});

describe('multi-size ICO keeps its AND-mask transparency', () => {
  /**
   * A format sweep once reported that multi-size ICO files "render fully opaque",
   * and it was the one item on that list with no fix, no test and no recorded
   * decision — so it stayed an open worry rather than a fact either way.
   *
   * It does not reproduce. Built to spec, with a 1bpp AND mask marking a
   * transparent border, single-entry and multi-entry files both decode with the
   * mask intact. What was missing was never a fix; it was this test.
   */
  // 24bpp ON PURPOSE, and this is the whole point of the fixture. A 32bpp payload
  // carries its own alpha, and `applyAndMask` returns early for it —
  // `bitCount === 32 && hasAnyAlpha(image)` — so a 32bpp fixture tests the alpha
  // channel and leaves the mask path completely unexercised. The first version of
  // this test did exactly that and survived neutering `applyAndMask` entirely.
  // At 24bpp there is no alpha channel, so the AND mask is the only thing that can
  // make a pixel transparent.
  const entry = (size: number) => {
    const rowBytes = Math.ceil(size * 3 / 4) * 4;  // 24bpp rows pad to 4 bytes
    const xorLen = rowBytes * size;
    const maskRow = Math.ceil(size / 32) * 4;      // 1bpp rows pad to 4 bytes
    const andLen = maskRow * size;
    const hdr = Buffer.alloc(40);
    hdr.writeUInt32LE(40, 0);
    hdr.writeInt32LE(size, 4);
    hdr.writeInt32LE(size * 2, 8);                 // height is doubled: XOR + AND
    hdr.writeUInt16LE(1, 12);
    hdr.writeUInt16LE(24, 14);
    hdr.writeUInt32LE(xorLen + andLen, 20);
    const xor = Buffer.alloc(xorLen);
    const and = Buffer.alloc(andLen);
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const inside = x > size / 4 && x < size * 3 / 4 && y > size / 4 && y < size * 3 / 4;
        const o = (size - 1 - y) * rowBytes + x * 3;  // BMP rows run bottom-up
        xor[o] = 30; xor[o + 1] = 60; xor[o + 2] = 200;
        if (!inside) and[(size - 1 - y) * maskRow + (x >> 3)] |= 0x80 >> (x & 7);
      }
    }
    return Buffer.concat([hdr, xor, and]);
  };

  const build = (sizes: number[]) => {
    const imgs = sizes.map(entry);
    const dir = Buffer.alloc(6 + 16 * sizes.length);
    dir.writeUInt16LE(0, 0);
    dir.writeUInt16LE(1, 2);
    dir.writeUInt16LE(sizes.length, 4);
    let off = dir.length;
    sizes.forEach((s, i) => {
      const b = 6 + i * 16;
      dir.writeUInt8(s, b); dir.writeUInt8(s, b + 1);
      dir.writeUInt16LE(1, b + 4); dir.writeUInt16LE(24, b + 6);
      dir.writeUInt32LE(imgs[i].length, b + 8);
      dir.writeUInt32LE(off, b + 12);
      off += imgs[i].length;
    });
    return Buffer.concat([dir, ...imgs]);
  };

  const transparentShare = (img: { data: Uint8ClampedArray }) => {
    let clear = 0;
    for (let i = 3; i < img.data.length; i += 4) if (img.data[i] === 0) clear++;
    return clear / (img.data.length / 4);
  };

  it.each([[[32]], [[16, 32]], [[16, 32, 48]]])('preserves the mask for sizes %j', async (sizes) => {
    const { loadAnyAsRaster } = await import('../src/api.js');
    const { image } = await loadAnyAsRaster(build(sizes as number[]), 'test.ico');
    // The border is transparent by construction and is most of the frame.
    expect(transparentShare(image), 'the AND mask was dropped').toBeGreaterThan(0.5);
    // And the centre must still be painted, so this is not "everything is clear".
    const mid = ((image.height >> 1) * image.width + (image.width >> 1)) * 4;
    expect(image.data[mid + 3]).toBe(255);
  });

  it('picks the largest entry from a multi-size file', async () => {
    const { loadAnyAsRaster } = await import('../src/api.js');
    const { image } = await loadAnyAsRaster(build([16, 32, 48]), 'test.ico');
    expect(image.width).toBe(48);
  });
});
