import { basename } from 'node:path';
import { gzipSync } from 'node:zlib';
import { decodeRaster, looksLikeSvg, type DecodeOptions } from './io/decode.js';
import { encodeRaster, type EncodeOptions } from './io/encode.js';
import { rasterizeSvg, type RasterizeOptions } from './io/rasterize.js';
import { packRgba } from './image.js';
import { compareImages, type CompareOptions } from './metrics/index.js';
import type {
  QualityReport, RasterImage, SizeBudgetReport, SourceMeta, VectorizeMode, VectorizeResult,
} from './types.js';
import { measureSvgComplexity, type SvgComplexity } from './svg/budget.js';
import { vectorizeEmbed, type EmbedOptions } from './vectorize/embed.js';
import { vectorizeExact, type ExactOptions } from './vectorize/exact.js';
import { vectorizePixels, type PixelVectorizeOptions } from './vectorize/pixel.js';
import { trace, TRACE_DEFAULTS, type TraceOptions } from './vectorize/trace.js';
import { heapLoopBudget } from './io/loop-budget.js';

export const VERSION = '2.1.1';

const GENERATOR = `Generated by vecline v${VERSION}`;

/**
 * Bytes the user actually receives, not bytes on disk.
 *
 * The comparison this feeds is between path data and base64. Base64 is
 * incompressible; path data gzips about 5x. Judging them raw therefore hands the
 * raster a systematic advantage it does not have in transit — measured, the two
 * disagree by 3.9x in opposite directions on alpha-dice.
 *
 * `level: 6` is the default most servers use, so this estimates what is actually
 * served rather than the best case.
 */
function gzipBytes(svg: string): number {
  return gzipSync(Buffer.from(svg), { level: 6 }).length;
}


export type VectorizeModeOption = VectorizeMode | 'auto' | 'lossless';

export type Preset = 'auto' | 'logo' | 'lineart' | 'poster' | 'photo' | 'detailed' | 'pixelart' | 'exact';

/**
 * Presets are starting points, not straitjackets — every field stays
 * overridable. They exist because the useful parameter combinations cluster by
 * *what kind of picture it is*, and asking someone to guess a Douglas–Peucker
 * tolerance is a bad interface.
 */
export const PRESETS: Record<Exclude<Preset, 'auto' | 'pixelart' | 'exact'>, TraceOptions> = {
  // Tolerances retuned after the curve-fit diagnosis. `logo` and `lineart` keep
  // a higher value (0.6) because there a large arc should stay a few smooth,
  // editable Béziers rather than a fine polygon — that is the whole point of a
  // logo tracer. `poster`, `photo` and `detailed` favour accuracy, where the
  // measured win is largest; `photo` at the old 1.4 was the worst setting in the
  // whole table.
  // `subpixel` and `precision: 1` are here and nowhere else, and the sweep that
  // decided that is worth recording because three of the five presets failed it.
  //
  // Sub-pixel edge extraction is what lets the curve fitter run at all (see
  // `subpixel.ts`), and on the two presets that already sit above the fitter's
  // engagement threshold it buys a lot for less geometry:
  //
  //   logo      +1.84 dB @4x, +1.68 @3.902x, true segments -21.2%
  //   lineart   +1.92 dB @4x, +1.74 @3.902x, true segments -19.2%
  //
  // It costs bytes — logo x1.80 raw / x2.90 gzip, lineart x2.08 / x3.61 across the
  // twelve corpus inputs — and time, x1.49 and x1.77. That trade is worth taking
  // where someone has said "this is a logo" and wants editable curves.
  //
  // It is NOT worth taking anywhere else, measured rather than assumed:
  //
  // - `detailed` couples tolerance/fitError at 0.3, which is *inside* the fitter's
  //   dead zone, so it emits zero curve segments today. Sub-pixel input there does
  //   not simplify an existing fit, it creates one and pays full price: **more**
  //   geometry (+10.1% true segments), x4.07 raw and x6.66 gzip bytes, x2.83 time,
  //   worse on 12 of 12 inputs — and it loses accuracy on the statistic these
  //   presets were tuned on (photo-cat SSIM 0.8645 -> 0.7003).
  // - `poster` is the same story more mildly: x1.87 raw, x3.53 gzip, only -7.2%
  //   segments, and SSIM down on photographs.
  // - `photo` is untouched on purpose; see its own note below.
  //
  // `precision: 1` is a separate, free win and applies only here for the same
  // reason: -13.3% raw and -17.0% gzip for -0.001 dB. It pays for itself because
  // sub-pixel coordinates are fractional, and a fractional coordinate costs both
  // more characters and worse compression (integers gzip ~5.8x, fractionals ~2.7x).
  logo: {
    colors: 16, minArea: 8, tolerance: 0.6, fitError: 0.6, cornerAngle: 75,
    subpixel: true, precision: 1,
  },
  lineart: {
    colors: 6, minArea: 4, tolerance: 0.6, fitError: 0.6, cornerAngle: 60,
    subpixel: true, precision: 1,
  },
  poster: { colors: 32, minArea: 12, tolerance: 0.5, fitError: 0.5, cornerAngle: 80 },
  // `photo` carries no minArea/tolerance/cornerAngle overrides on purpose. It
  // used to force `minArea: 16, cornerAngle: 90, colors: 64` — the same mistake
  // `autoTracePreset` documents having removed — and `npm run compare` caught
  // the result: a preset named "photo" was *worse than auto on photographs*.
  // Despeckling at 16px erases exactly the fine detail — feathers, hair,
  // foliage — that a photograph is made of, and the extra 16 colours never paid
  // for themselves.
  //
  // Re-measured against the shipped path, because the figures recorded here
  // originally were not reproducible from it. The old arm still reproduces
  // exactly (parrots 0.7868 SSIM / 262 KB, portrait 0.6983 / 439 KB) since it
  // passes an explicit `minArea`. This preset does not, and "no override" no
  // longer means "adaptive": `TRACE_DEFAULTS.minArea` is 0 and is spread over
  // every call site below, while the adaptive floor only applies when `minArea`
  // is `undefined`. So the preset now traces with no despeckling at all.
  //
  // What that actually buys, measured:
  //
  //   parrots   0.8340 SSIM / 640 KB   vs old 0.7868 / 262 KB
  //   portrait  0.9127 SSIM / 1366 KB  vs old 0.6983 / 439 KB
  //
  // Quality is far ahead — the point above still holds, and more strongly than
  // the original numbers suggested. But this is a trade, not a clean sweep: it
  // costs 2.4x to 3.1x the bytes. Any claim that it wins "on every axis at
  // once" is false and should not be restored.
  photo: { colors: 48, gradients: true },
  detailed: { colors: 48, minArea: 2, tolerance: 0.3, fitError: 0.3, cornerAngle: 60 },
};

export interface VectorizeOptions {
  /**
   * `auto` inspects the image and picks. `lossless` guarantees a bit-exact
   * result, preferring real geometry (`pixel`) and falling back to `embed`.
   */
  mode?: VectorizeModeOption;
  preset?: Preset;
  /** Render the result and measure it against the input. */
  verify?: boolean;
  /** Escalate trace settings until mean SSIM reaches this. Implies `verify`. */
  targetSsim?: number;
  /** Escalate trace settings until PSNR reaches this many dB. Implies `verify`. */
  targetPsnr?: number;
  /** Upper bound on palette size during refinement. */
  maxColors?: number;
  /** Refinement attempts before giving up and returning the best so far. */
  maxRefineSteps?: number;
  /**
   * Size budget: relax trace settings until the SVG fits this many bytes, and
   * report the measured accuracy it cost ({@link VectorizeResult.budget}).
   * Implies verification, since the receipt is the point.
   */
  maxBytes?: number;
  /**
   * Complexity budget: relax until the geometry carries at most this many
   * anchor points. Targeted separately from {@link maxBytes} because the two
   * do not move together — precision trims bytes without removing a node.
   */
  maxNodes?: number;
  /**
   * What `lossless` optimises for once exactness is assured.
   *
   * `auto` (default) keeps real editable geometry whenever it is not
   * unreasonably larger than the alternative — see {@link maxGeometryRatio}.
   * `geometry` insists on real paths at any size. `size` always takes the
   * smallest exact result, which on photographs is the embedded bitmap.
   */
  losslessPrefer?: 'auto' | 'geometry' | 'size';
  /**
   * Under `auto`, how many times larger real geometry may be than the smallest
   * exact alternative before it stops being worth it. Default 4.
   */
  maxGeometryRatio?: number;
  trace?: TraceOptions;
  embed?: EmbedOptions;
  pixel?: PixelVectorizeOptions;
  exact?: ExactOptions;
  compare?: CompareOptions;
  /** `<title>` for the generated document. */
  title?: string;
  /** Suppress the generator comment. */
  noGenerator?: boolean;
}

export interface VectorizeInput {
  image: RasterImage;
  meta: SourceMeta;
  bytes: Uint8Array;
}

/** Read and normalise a raster file. */
export async function loadRaster(
  path: string | Uint8Array,
  opts?: DecodeOptions,
): Promise<VectorizeInput> {
  const { image, meta, bytes } = await decodeRaster(path, opts);
  return { image, meta, bytes };
}

/**
 * Convert a raster image to SVG.
 *
 * The returned `quality` field, when verification runs, is measured against the
 * actual rendered output — not estimated from the parameters. If it says the
 * result is lossless, the file was rendered and compared pixel by pixel.
 */
export async function vectorize(
  input: VectorizeInput,
  opts: VectorizeOptions = {},
): Promise<VectorizeResult> {
  const started = Date.now();
  const notes: string[] = [];
  const generator = opts.noGenerator ? undefined : GENERATOR;
  const wantsTarget = opts.targetSsim !== undefined || opts.targetPsnr !== undefined;
  const verify = opts.verify || wantsTarget;

  // Strict lossless is its own path: it verifies every candidate by rendering
  // and refuses to return anything that is not bit-exact.
  if (opts.mode === 'lossless' || opts.preset === 'exact') {
    const strict = await runLossless(input, opts, generator, notes);
    strict.elapsedMs = Date.now() - started;
    strict.notes = notes;
    return strict;
  }

  const mode = resolveMode(input, opts, notes);

  let result: VectorizeResult;
  switch (mode) {
    case 'embed':
      result = await runEmbed(input, opts, generator, notes);
      break;
    case 'pixel':
      result = runPixel(input, opts, generator, notes);
      break;
    case 'trace':
      result = await runTrace(input, opts, generator, notes);
      break;
  }

  if (verify && !result.quality) {
    result.quality = await verifySvg(result.svg, input.image, opts.compare);
  }

  // Auto mode picked a strategy from image statistics before seeing the result.
  // If that guess produced something an exact alternative beats on *both* size
  // and accuracy, take the alternative — there is no trade-off to weigh.
  //
  // Exempt an explicit preset. This check fires on exactly the images a tracing
  // preset is for — its own docstring names "a logo with 194 colours and soft
  // edges" — so without the exemption, making a preset select trace mode would be
  // inert: the trace would be built and then swapped straight back for a base64
  // copy. Someone who typed `--preset logo` has said which *kind* of output they
  // want, and "smaller" is not the axis they asked about. Plain `auto` is
  // unchanged and still takes the exact copy when it dominates.
  const presetChose = opts.preset !== undefined && opts.preset !== 'auto';
  if ((opts.mode ?? 'auto') === 'auto' && !presetChose && result.mode === 'trace') {
    const better = await findDominatingExact(input, result, opts, notes);
    if (better) result = better;
  }

  if (verify && !result.quality) {
    result.quality = await verifySvg(result.svg, input.image, opts.compare);
  }

  // Measurement outranks assertion. A mode can be lossless by construction and
  // still not round-trip through a particular renderer — an embedded JPEG is the
  // usual case, where the payload survives intact but the renderer's decoder
  // rounds differently. Reporting the construction-time claim when a measurement
  // contradicts it would be the one lie this tool must not tell.
  if (result.quality) {
    if (!result.quality.lossless && result.lossless) {
      notes.push(
        `Verification found ${result.quality.pixels - result.quality.exactPixels} ` +
          `differing pixel(s) (max ${result.quality.maxChannelDiff}/255). The mode is ` +
          `exact by construction, so this is the renderer's decoder, not lost data.`,
      );
    }
    result.lossless = result.quality.lossless;
  }

  result.elapsedMs = Date.now() - started;
  result.notes = notes;
  return result;
}

/** Render an SVG at the reference image's exact size and compare the two. */
export async function verifySvg(
  svg: string,
  reference: RasterImage,
  compare?: CompareOptions,
  rasterizeOpts?: RasterizeOptions,
): Promise<QualityReport> {
  let rendered = await rasterizeSvg(svg, { ...rasterizeOpts });
  if (rendered.image.width !== reference.width || rendered.image.height !== reference.height) {
    // Force the exact reference size; an off-by-one from unit resolution would
    // otherwise make the comparison impossible rather than merely imprecise.
    rendered = await rasterizeSvg(svg, { ...rasterizeOpts, width: reference.width });
  }
  return compareImages(reference, rendered.image, compare);
}

// ---------------------------------------------------------------------------
// Mode selection
// ---------------------------------------------------------------------------

interface Flatness {
  distinctColors: number;
  capped: boolean;
  /** Horizontal runs per pixel. Near 0 is flat artwork, near 1 is noise. */
  runRatio: number;
  /**
   * Mean absolute deviation from the local mean, measured only AWAY from edges.
   *
   * This is the precondition for sub-pixel refinement, not a content guess.
   * Refinement recovers where an edge fell by inverting the anti-aliasing
   * coverage across it; that inversion assumes the only variation near a
   * boundary IS coverage. Interior noise is variation that is not, and it gets
   * read as edge displacement.
   */
  interiorNoise: number;
}

/**
 * Two cheap signals separate "artwork" from "photograph" reliably:
 * the number of distinct colours, and how often colour changes along a scanline.
 * A screenshot can have thousands of colours yet still be mostly flat; a
 * gradient-heavy photo has both high counts and high run density.
 */
export function measureFlatness(img: RasterImage, colorCap = 4096): Flatness {
  const seen = new Set<number>();
  const d = img.data;
  let runs = 0;
  let capped = false;
  let prev = -1;

  for (let y = 0; y < img.height; y++) {
    prev = -1;
    for (let x = 0; x < img.width; x++) {
      const o = (y * img.width + x) * 4;
      const a = d[o + 3];
      const key = a === 0 ? 0 : packRgba(d[o], d[o + 1], d[o + 2], a);
      if (key !== prev) { runs++; prev = key; }
      if (!capped) {
        seen.add(key);
        if (seen.size > colorCap) capped = true;
      }
    }
  }

  // Second pass, off the edges: how much does a pixel differ from its own
  // neighbourhood where there is no boundary to explain it? Cheap, and the only
  // thing that predicts whether refinement will help or hurt.
  const lum = (x: number, y: number): number => {
    const o = ((y * img.width) + x) * 4;
    return (d[o] + d[o + 1] + d[o + 2]) / 3;
  };
  let noiseSum = 0;
  let noiseN = 0;
  for (let y = 1; y < img.height - 1; y++) {
    for (let x = 1; x < img.width - 1; x++) {
      const gx = lum(x + 1, y) - lum(x - 1, y);
      const gy = lum(x, y + 1) - lum(x, y - 1);
      if (Math.hypot(gx, gy) > 24) continue;   // a real boundary, not interior
      let mean = 0;
      for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) mean += lum(x + dx, y + dy);
      noiseSum += Math.abs(lum(x, y) - mean / 9);
      noiseN++;
    }
  }

  return {
    distinctColors: seen.size,
    capped,
    runRatio: runs / (img.width * img.height),
    interiorNoise: noiseN > 0 ? noiseSum / noiseN : 0,
  };
}

/**
 * Interior noise above which sub-pixel refinement is switched off.
 *
 * Measured, with the same images clean and re-encoded, so the split is not a
 * content guess:
 *
 *   PNG rendered from vector   0.014 - 0.219   refinement worth +3.01 dB at scale
 *   the same at JPEG q40       0.577 - 1.079   refinement costs 0.03-0.10 SSIM
 *   logo-tux.png               0.799           costs 0.058 SSIM
 *   photo-parrots.png          1.583
 *   a 100x100 JPEG sticker     5.061           costs 0.095 SSIM and 3.6x bytes
 *
 * No overlap: the clean set tops out at 0.219 and the noisy set starts at 0.577.
 * 0.3 sits inside that gap and is deliberately nearer the clean end, because the
 * two mistakes are not symmetric — refining clean input that did not need it
 * costs a little size, while refining noisy input costs accuracy AND 3x the
 * bytes.
 *
 * This replaces a genuinely bad rule. Refinement was previously switched off by
 * `flat.capped`, a >4096 colour count, which JPEG noise trips on a cartoon — so
 * the reported image that motivated curves-by-default went back to zero curves.
 * A colour count is a proxy for content; this is the mechanism's own
 * precondition.
 */
const REFINE_NOISE_LIMIT = 0.3;

function resolveMode(
  input: VectorizeInput,
  opts: VectorizeOptions,
  notes: string[],
): VectorizeMode {
  if (opts.preset === 'pixelart') return 'pixel';
  // `lossless` and the `exact` preset never reach here — `vectorize` routes them
  // to `runLossless`, which decides by measuring candidates rather than guessing.
  if (opts.mode && opts.mode !== 'auto' && opts.mode !== 'lossless') return opts.mode;

  // An explicit preset outranks the auto heuristics.
  //
  // Until now it did not, and the consequence was total rather than subtle: this
  // function read `opts.preset` for exactly two values, `'pixelart'` above and
  // `'exact'` in `vectorize`. Every other preset was consulted only inside
  // `runTrace`, which is never reached when the statistics choose pixel — so
  // `logo`, `lineart`, `poster`, `photo` and `detailed` all produced output
  // *byte-identical to `auto`*. Measured on a rasterised vector original: all five
  // returned the same sha256, the same 40,630 bytes and the same 57 shapes; and on
  // this project's own `logo-tux.png`, `--preset logo` returned a 16 KB base64
  // raster. Naming a tracing preset is a statement that a resolution-independent
  // result is wanted, and it was being ignored.
  //
  // Placed *after* the `opts.mode` check so `--mode pixel --preset logo` still
  // honours the more specific flag, and the note says how to get an exact copy
  // back, because for a flat logo that genuinely is the smaller answer.
  if (opts.preset !== undefined && opts.preset !== 'auto') {
    notes.push(
      `Preset '${opts.preset}' selected trace mode: naming a preset outranks the ` +
        `auto heuristics, which would otherwise have measured this image and may ` +
        `have chosen an exact copy. Use --mode pixel or --mode embed for that.`,
    );
    return 'trace';
  }

  const flat = measureFlatness(input.image, 4096);
  if (isPixelFeasible(input.image, flat)) {
    notes.push(
      `Auto-selected pixel mode: ${flat.distinctColors} distinct colours, ` +
        `${(flat.runRatio * 100).toFixed(1)}% run density. Output is bit-exact.`,
    );
    return 'pixel';
  }

  notes.push(
    `Auto-selected trace mode: ${flat.capped ? '>4096' : flat.distinctColors} distinct colours, ` +
      `${(flat.runRatio * 100).toFixed(1)}% run density. Tracing approximates; ` +
      `use --mode embed if you need this image reproduced exactly.`,
  );
  return 'trace';
}

/** Ceiling on rectangles before a pixel-mode file stops being worth having. */
const PIXEL_RECT_BUDGET = 600_000;
/** Run density below which greedy meshing still folds many pixels per rectangle. */
const FLAT_RUN_RATIO = 0.12;
/** Palette size below which an image is flat artwork whatever its run density. */
const FLAT_COLOR_COUNT = 64;

/**
 * Decide whether pixel mode would produce a file worth having.
 *
 * Two independent signals each indicate genuinely flat content, and either one
 * is enough:
 *
 * - **Long colour runs.** Greedy meshing folds an order of magnitude of pixels
 *   into each rectangle, so the output is real geometry rather than a bitmap
 *   spelled out in `<rect>` elements.
 * - **A small palette.** A 32×32 sprite changes colour every few pixels, so its
 *   run density looks photographic — but four colours across a thousand pixels
 *   is unmistakably artwork, and pixel mode handles it perfectly.
 *
 * Requiring both would push sprites to the tracer, which is exactly wrong: pixel
 * art is the one case where exact output is both achievable and expected.
 * A hard rectangle budget then bounds the cost regardless of which signal fired.
 */
function isPixelFeasible(img: RasterImage, flat: Flatness): boolean {
  if (flat.capped || flat.distinctColors > 4096) return false;

  // `runRatio` counts HORIZONTAL runs, so this product is the rectangle count
  // *before* greedy meshing merges anything vertically — an upper bound, and a
  // deliberately one-sided one. Measured against the real count it is tight:
  // 1.04x-1.62x, median 1.13x across the corpus, with zero images where the
  // bound and the truth land on opposite sides of the budget.
  //
  // It is blind to vertical coherence, and that blindness is unbounded rather
  // than merely loose: 1px-wide alternating stripes at 2000x2000 estimate
  // 4,000,000 against a true 2,000, so a two-colour image whose exact output is
  // 14.8 KB is refused. Left alone deliberately, because nothing realistic
  // reaches it — the input must have runRatio near 1 AND near-perfect vertical
  // coherence at once. Real vertical structure has *few* runs per row, so it is
  // not close: a 3000x1200 barcode estimates 145,200, an A4 ruled form at
  // 400 dpi 109,256, and 1920x1080 colour bars 7,560, all against a 600,000
  // budget. Widening the estimate to min(horizontal, vertical) runs would cost
  // a second cache-hostile pass in what is deliberately a cheap pre-filter, and
  // would trade a measured-tight bound for an unproven one.
  const estimatedRects = flat.runRatio * img.width * img.height;
  if (estimatedRects > PIXEL_RECT_BUDGET) return false;

  return flat.runRatio <= FLAT_RUN_RATIO || flat.distinctColors <= FLAT_COLOR_COUNT;
}

/**
 * Look for an exact result that beats an approximate one outright.
 *
 * Auto mode chooses from colour count and run density, before anything has been
 * produced. Those signals misjudge anti-aliased artwork badly: a logo with 194
 * colours and soft edges reads as "too varied for exact geometry", goes to the
 * tracer, and comes back **eight times larger than the source file and still
 * approximate** — while an embedded copy would have been smaller *and* exact.
 *
 * A user cannot be expected to notice that, so this checks. It only runs when
 * the traced output is already suspiciously large (bigger than the input file),
 * which keeps the extra work off the common path where tracing did its job.
 *
 * The bar is deliberately dominance, not preference: the alternative must be
 * both smaller and bit-exact. Anything less is a genuine trade-off, and those
 * belong to the caller.
 */
/**
 * What `auto` actually optimises for, measured — because three separate
 * investigations have now reached for this question and each assumed a
 * different mechanism.
 *
 * **`auto` never returns a Bézier.** Swept across 39 real images — flat icons,
 * multi-colour logos, alpha-heavy art and photographs — the default produced
 * zero curve commands on every one. Not by one route but by three, which is why
 * it keeps being rediscovered as a new bug:
 *
 * - flat few-colour art goes to `pixel` (30 of 39), which is bit-exact
 *   rectangles — see {@link isPixelFeasible};
 * - richer artwork goes to `trace`, and then this function finds an exact copy
 *   that is smaller *and* bit-exact and takes it (7 of the 9 that reached trace;
 *   on `logo-tux.png`, 16,221 bytes against the trace's 107,926);
 * - what survives as a trace still emits no curves, because at the shipped
 *   `tolerance: 0.4` the fitter does not fire at all.
 *
 * That is a coherent contract, not three bugs: **`auto` optimises for fidelity
 * at the image's own resolution, and resolution independence is the axis it does
 * not weigh.** Every branch above is the right answer to "reproduce this image
 * as faithfully and cheaply as possible" and the wrong answer to "give me
 * something that scales".
 *
 * The redeeming property, also measured: it is never silent. All 39 carried a
 * note naming what happened and how to get curves instead — 0 non-scalable
 * results without an explanation. Keep it that way; a default that quietly
 * hands back a bitmap in an SVG wrapper is the actual defect, not this one
 * choosing exactness.
 *
 * Users who want curves have `--mode trace`, `--preset logo`, or `--tolerance`.
 */
async function findDominatingExact(
  input: VectorizeInput,
  traced: VectorizeResult,
  opts: VectorizeOptions,
  notes: string[],
): Promise<VectorizeResult | null> {
  // A trace that produced real curves is not comparable to a raster on size
  // alone, so it is not "dominated" by one that happens to be smaller.
  //
  // This mattered the moment curves became the default. Refinement makes a trace
  // roughly 2.35x larger gzipped, which pushed far more images over the line
  // here — so switching curves on in the tracer produced *fewer* curves from
  // `auto`, because this function then swapped them for a bitmap. Two tests
  // caught it by expecting 'trace' and getting 'embed'.
  //
  // The original reasoning stands where it applies: when the trace emitted no
  // curve commands at all it is already a bitmap in an SVG wrapper, and an exact
  // copy that is smaller beats it on every axis with nothing to trade. That case
  // still switches, and still says so.
  // TWO THINGS MEASURED HERE AND NOT ACTED ON, so the next reader does not
  // re-derive them.
  //
  // 1. This compares RAW bytes, and raw systematically favours the embed: base64
  //    is incompressible while path data gzips about 5x. On alpha-dice the two
  //    disagree by 3.9x in opposite directions — raw picks embed (318.0 vs 292.7
  //    KB), gzip picks trace (56.3 vs 219.2 KB). Measured across 13 images the
  //    decision changes on 1 of them, so this is real but rare, and "what ships"
  //    is genuinely ambiguous — raw is the file on disk, gzip is the bytes on the
  //    wire. Not changed on a 1-in-13 effect with no clearly right answer.
  //
  // 2. The deeper issue is the objective, not the units. This function weighs
  //    size and exactness. A vector's value is that it SCALES, and that is not in
  //    the comparison at all — so a bit-exact raster will always look like it
  //    dominates a trace of similar size, for a tool whose purpose is to produce
  //    geometry. On the reported 100x100 sticker the embed really is smaller
  //    (10.7 vs 11.1 KB gzipped) and really is bit-exact, and returning it is
  //    still arguably the wrong answer to "vectorise this".
  //
  const tracedCurves = [...traced.svg.matchAll(/\sd="([^"]*)"/g)]
    .reduce((n, m) => n + (m[1].match(/[CcSsQqTtAa]/g) ?? []).length, 0);
  if (tracedCurves > 0) return null;

  const tracedBytes = Buffer.byteLength(traced.svg);
  const tracedGzip = gzipBytes(traced.svg);
  // Someone who typed `convert x.jpg x.svg` asked for geometry; `--mode embed`
  // exists and is named for the other thing. So real paths are kept unless the
  // exact raster is dramatically smaller, not merely smaller.
  const geometryRatio = opts.maxGeometryRatio ?? 4;
  // `meta` is required by the type, but plain-JS callers reach here through the
  // CJS build with `vectorize({ image })` — which works for the pixel and embed
  // paths and then crashes here, only when auto happens to pick trace. Nothing
  // downstream needs the comparison if we do not know the source size.
  if (input.meta === undefined || tracedBytes <= input.meta.bytes) return null;

  try {
    // `preserve` first because it is smaller and keeps the original file, then
    // `png` which always renders exactly. Asking for `auto` here would be a
    // trap: on a JPEG source it picks the preserved payload, which is smaller
    // but *not* bit-exact through the renderer, so the check would find no
    // dominating candidate and silently keep the worse traced result.
    let exact: Awaited<ReturnType<typeof vectorizeEmbed>> | null = null;
    let exactBytes = 0;
    let report: QualityReport | null = null;

    for (const strategy of ['preserve', 'png'] as const) {
      const candidate = await vectorizeEmbed(input.image, input.bytes, input.meta, {
        ...opts.embed, strategy,
        generator: opts.noGenerator ? undefined : GENERATOR,
        title: opts.title,
      });
      // Judged on SHIPPED bytes, and with a margin.
      //
      // Raw byte counts favour the raster twice over: base64 does not compress,
      // while path data gzips about 5x, so a trace that is smaller on the wire
      // looks larger on disk. On alpha-dice the two disagree by 3.9x in opposite
      // directions. Comparing what the user actually receives removes that.
      //
      // The margin is the substantive part. This used to swap on ANY win — a
      // trace was discarded for a raster 0.4 KB smaller, trading away the one
      // property a vector has. `maxGeometryRatio` already expresses exactly this
      // trade for `lossless` mode; auto had no such guard and should.
      const bytes = gzipBytes(candidate.svg);
      if (bytes * geometryRatio >= tracedGzip) continue;

      const measured = await verifySvg(candidate.svg, input.image, opts.compare);
      if (!measured.lossless) continue;

      exact = candidate;
      exactBytes = bytes;
      report = measured;
      break;
    }

    if (!exact || !report) return null;

    // The accuracy clause is conditional because the accuracy is usually
    // unknown here. `quality` is only populated when the caller asked to
    // verify, and this runs before that — so the previous unconditional
    // `traced.quality?.ssim ?? 0` printed "SSIM 0.0000" on the default
    // `convert` path for every input it rejected. Identical bytes, identical
    // decision, and a figure that was the fallback rather than a measurement:
    // the same trace scores 0.988411 when actually verified.
    //
    // Measuring it here to fill the sentence would mean rendering and scoring
    // an SVG we are about to discard, on the common path, to print a number
    // that decides nothing — the choice below is byte-dominance, not accuracy.
    // So say what is known instead.
    const accuracy = traced.quality ? ` at SSIM ${traced.quality.ssim.toFixed(4)}` : '';
    notes.push(
      `Switched to embed: tracing produced ${formatCount(tracedGzip)} bytes gzipped${accuracy}, ` +
        `while an exact copy is ${formatCount(exactBytes)} — more than ${geometryRatio}x ` +
        `smaller, and bit-exact. Below that margin the geometry is kept, because ` +
        `scaling is what it is for. Use --mode trace to force ` +
        `real curves.`,
    );

    return {
      svg: exact.svg,
      width: input.image.width,
      height: input.image.height,
      mode: 'embed',
      shapes: 1,
      colors: 0,
      lossless: true,
      quality: report,
      notes,
      elapsedMs: 0,
      settled: {
        mime: exact.mime,
        payloadBytes: exact.payloadBytes,
        bytesPreserved: exact.bytesPreserved,
        rejectedTraceBytes: tracedBytes,
      },
    };
  } catch {
    // The comparison is an optimisation; failing it just keeps the traced result.
    return null;
  }
}

// ---------------------------------------------------------------------------
// Strict lossless
// ---------------------------------------------------------------------------

interface LosslessCandidate {
  svg: string;
  mode: VectorizeMode;
  shapes: number;
  colors: number;
  /** Short description used in notes and errors. */
  label: string;
  settled?: Record<string, number | string | boolean>;
  report?: QualityReport;
}

/**
 * Produce a bit-exact SVG, or fail loudly.
 *
 * The guarantee is enforced by measurement, not by construction: every
 * candidate is rendered back to pixels and compared against the source, and
 * anything that is not bit-identical is discarded. If nothing survives, this
 * throws rather than returning a near-miss — silently downgrading a lossless
 * request is the one failure mode that would make the promise worthless.
 *
 * Candidates are tried in order of how useful the result is:
 *
 * 1. **Exact geometry** — real editable paths, either rectangles or contours,
 *    whichever encodes smaller.
 * 2. **Embed, original bytes preserved** — gives a byte-identical round trip of
 *    the source *file*, not merely of its pixels.
 * 3. **Embed, re-encoded as PNG** — always renders exactly, at the cost of no
 *    longer carrying the original file.
 *
 * Step 2 sits above step 3 because it is strictly better when it works, and it
 * usually does; it fails for JPEG sources, where the renderer's decoder rounds
 * its inverse DCT differently from the reference decoder.
 */
async function runLossless(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const prefer = opts.losslessPrefer ?? 'auto';
  const maxRatio = opts.maxGeometryRatio ?? 4;
  const title = opts.title;
  const candidates: LosslessCandidate[] = [];

  // --- 1. Real geometry ---
  try {
    const exact = vectorizeExact(input.image, {
      ...opts.pixel, ...opts.exact, generator, title,
    });
    candidates.push({
      svg: exact.svg,
      mode: 'pixel',
      shapes: exact.shapes,
      colors: exact.colors,
      label: `exact geometry (${exact.strategy})`,
      settled: {
        strategy: exact.strategy,
        rectangleBytes: exact.sizes.rectangles,
        ...(exact.sizes.contours !== undefined ? { contourBytes: exact.sizes.contours } : {}),
      },
    });
  } catch (err) {
    notes.push(`Exact geometry unavailable: ${(err as Error).message}`);
  }

  // --- 2 & 3. Embedded payloads ---
  const requested = opts.embed?.strategy;
  const strategies: Array<EmbedOptions['strategy']> =
    requested && requested !== 'auto' ? [requested] : ['preserve', 'png'];

  for (const strategy of strategies) {
    try {
      const out = await vectorizeEmbed(input.image, input.bytes, input.meta, {
        ...opts.embed, strategy, generator, title,
      });
      candidates.push({
        svg: out.svg,
        mode: 'embed',
        shapes: 1,
        colors: 0,
        label: `embed (${out.bytesPreserved ? 'original bytes preserved' : out.mime})`,
        settled: {
          mime: out.mime,
          payloadBytes: out.payloadBytes,
          bytesPreserved: out.bytesPreserved,
        },
      });
    } catch (err) {
      notes.push(`Embed strategy "${strategy}" failed: ${(err as Error).message}`);
    }
  }

  // Two strategies can converge on the same output — a BMP source has no
  // preservable payload, so both `preserve` and `png` re-encode identically.
  // Verifying and reporting it twice is just noise.
  const unique: LosslessCandidate[] = [];
  for (const candidate of candidates) {
    if (!unique.some((seen) => seen.svg === candidate.svg)) unique.push(candidate);
  }

  // --- Verify every candidate; keep only the provably exact ones. ---
  const exactOnes: LosslessCandidate[] = [];
  const rejected: string[] = [];

  for (const candidate of unique) {
    const report = await verifySvg(candidate.svg, input.image, opts.compare);
    candidate.report = report;
    if (report.lossless) exactOnes.push(candidate);
    else {
      rejected.push(
        `${candidate.label}: ${report.pixels - report.exactPixels} pixel(s) differ ` +
          `(max ${report.maxChannelDiff}/255)`,
      );
    }
  }

  if (exactOnes.length === 0) {
    throw new Error(
      `Could not produce a bit-exact SVG for this input. Tried:\n` +
        rejected.map((r) => `  - ${r}`).join('\n') +
        `\nThis should not happen; please report it with the input image.`,
    );
  }

  // --- Choose among the survivors. ---
  const geometry = exactOnes.find((c) => c.mode === 'pixel');
  const smallest = [...exactOnes].sort((a, b) => a.svg.length - b.svg.length)[0];

  let chosen: LosslessCandidate;
  let rationale: string | null = null;

  if (prefer === 'size' || !geometry) {
    chosen = smallest;
  } else if (prefer === 'geometry') {
    chosen = geometry;
  } else {
    // `auto`: real geometry is worth a premium, but not an unbounded one. A
    // photograph encodes exactly as roughly one rectangle per pixel, which is a
    // multi-megabyte file that is vector in name only.
    const ratio = geometry.svg.length / smallest.svg.length;
    if (ratio <= maxRatio) {
      chosen = geometry;
    } else {
      chosen = smallest;
      rationale =
        `Exact geometry would be ${ratio.toFixed(1)}x larger than the embedded bitmap ` +
        `(${formatCount(geometry.svg.length)} vs ${formatCount(smallest.svg.length)} bytes), ` +
        `so the bitmap was used. Both are bit-exact; pass --prefer geometry to force real paths.`;
    }
  }

  if (rejected.length > 0) {
    notes.push(`Rejected ${rejected.length} candidate(s) that were not bit-exact: ${rejected.join('; ')}.`);
  }
  for (const c of exactOnes) {
    if (c !== chosen) notes.push(`Alternative: ${c.label}, ${formatCount(c.svg.length)} bytes.`);
  }
  notes.push(`Verified bit-exact by rendering and comparing every pixel — ${chosen.label}.`);
  if (rationale) notes.push(rationale);
  else if (geometry && chosen === geometry && smallest !== geometry) {
    notes.push('Kept real geometry over the smaller embedded bitmap; pass --prefer size to invert that.');
  }

  return {
    svg: chosen.svg,
    width: input.image.width,
    height: input.image.height,
    mode: chosen.mode,
    shapes: chosen.shapes,
    colors: chosen.colors,
    lossless: true,
    quality: chosen.report,
    notes,
    elapsedMs: 0,
    settled: chosen.settled,
  };
}

// ---------------------------------------------------------------------------
// Per-mode runners
// ---------------------------------------------------------------------------

async function runEmbed(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const out = await vectorizeEmbed(input.image, input.bytes, input.meta, {
    ...opts.embed,
    generator,
    title: opts.title,
  });
  notes.push(...out.notes);
  if (out.bytesPreserved) {
    notes.push('Original file bytes preserved verbatim inside the SVG.');
  }
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'embed',
    shapes: 1,
    colors: 0,
    lossless: true,
    notes,
    elapsedMs: 0,
    settled: { mime: out.mime, payloadBytes: out.payloadBytes, bytesPreserved: out.bytesPreserved },
  };
}

function runPixel(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): VectorizeResult {
  const out = vectorizePixels(input.image, { ...opts.pixel, generator, title: opts.title });
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'pixel',
    shapes: out.shapes,
    colors: out.colors,
    lossless: true,
    notes,
    elapsedMs: 0,
    settled: { rects: out.rects },
  };
}

/**
 * Trace, then — if a quality target was given — escalate and try again.
 *
 * Each step doubles the palette and tightens the geometric tolerances, because
 * the two failure modes are different: too few colours shows up as banding,
 * too loose a tolerance shows up as rounded-off detail. Moving both keeps the
 * search short. The best result seen is kept, so a target that turns out to be
 * unreachable still returns the closest attempt rather than the last one.
 */
/**
 * When no preset is named, scale the trace settings to the content instead of
 * always using the lean 16-colour default. A photograph traced with 16 colours
 * bands visibly; a zero-config `convert photo.png out.svg` should give it a
 * photo-grade palette and gradient de-banding (which can only help). Flat artwork
 * keeps the lean default, which is already ideal — and is never sent here anyway,
 * since auto mode routes it to bit-exact pixel output first.
 */
function autoTracePreset(img: RasterImage, notes: string[]): TraceOptions {
  const flat = measureFlatness(img, 4096);

  // Sub-pixel refinement runs only where its own precondition holds.
  //
  // It recovers where an edge fell by inverting the anti-aliasing coverage
  // across it, which assumes the variation near a boundary IS coverage. Feed it
  // a noisy source and it inverts the noise, displacing vertices to where no
  // edge was. That is not a small effect: on the same images clean and at JPEG
  // q40, the accuracy it costs grows 10-25x (-0.003 SSIM clean, -0.032 to
  // -0.095 noisy) while it keeps charging 2.3-3.7x the bytes.
  //
  // Deliberately NOT a content-type guess. Two of those were tried and both
  // failed: a >4096 colour count put a JPEG cartoon in the same bucket as a
  // photograph, and a flat-neighbourhood share ranked that cartoon (11.3%)
  // below a genuine photograph (12.5%). `interiorNoise` measures the thing the
  // algorithm actually needs, and separates cleanly — see REFINE_NOISE_LIMIT.
  const refine: TraceOptions = {};
  if (flat.interiorNoise > REFINE_NOISE_LIMIT) {
    refine.subpixel = false;
    // The lattice straightness test fails on the same precondition, and it is
    // worth being explicit that this is one condition rather than two.
    //
    // Both assume a boundary came from a real geometric edge that the pixel grid
    // quantised. Sub-pixel refinement inverts the coverage ramp across such an
    // edge; the straightness test asks whether a run of vertices could have come
    // from one. Continuous tone has no such edges, so the first inverts noise and
    // the second finds spurious straightness in it — measured on the published
    // photo row, leaving it on took `trace auto` from 49.3 KB to 163.8 KB while
    // SSIM fell 0.8476 -> 0.8311. Worse and 3.3x larger.
    // Both stay off, and the second one is a conclusion I reached twice and had to
    // measure twice.
    //
    // The argument for re-enabling boundary simplification here is that `segment`
    // does not merely tolerate noise, it removes it — so the precondition is
    // established downstream rather than absent. That argument is wrong, because
    // the precondition is not "no noise", it is "this boundary came from a
    // straight geometric edge that the grid quantised". Segmentation removes grain;
    // it does not make a photograph's region boundaries straight. They are organic,
    // and a straightness test run over them manufactures a curve at every bend.
    //
    // Measured with segmentation on, against leaving simplification off:
    //
    //   sticker   0.9556 ->  0.8849 SSIM,   9.9 ->  15 KB,  3,894 curves
    //   logo-tux  0.9731 ->  0.9319 SSIM,  14.4 ->  25 KB,  4,724 curves
    //   parrots   ~0.81   ->  0.8174 SSIM,   72 -> 196 KB, 24,065 curves
    //
    // Worse on accuracy AND size on all three. Widening the band does not rescue
    // it either — 0.75 through 6.0 costs more accuracy and more bytes at every
    // step, up to 314 KB on the photograph. Curves are available on demand and are
    // not worth this by default.
    refine.latticeSimplify = false;
    notes.push(
      `Sub-pixel refinement and lattice simplification off: interior noise ` +
        `${flat.interiorNoise.toFixed(2)} exceeds ${REFINE_NOISE_LIMIT}, so there is no ` +
        `quantised geometric edge for either to read. Force them with --subpixel and ` +
        `--lattice-simplify if the source is cleaner than it measures.`,
    );
  }
  // Only the palette is widened (plus gradient de-banding for photos). minArea
  // and the fit tolerances are deliberately left to auto-scale: forcing a larger
  // minArea here despeckled fine detail — feathers, foliage — and cost more
  // accuracy than the extra colours bought back.
  if (flat.capped) {
    // Sub-pixel refinement STAYS ON here, and the story of why is worth keeping.
    //
    // It was switched off for photographs on the strength of the published bench
    // row: 49.3 -> 93.8 KB, 31.31 -> 30.82 dB, 0.8476 -> 0.8116 SSIM. Every axis
    // worse. But that row scores the output against the SOURCE at 1x, and at 1x
    // the lattice cannot lose — it *is* the source, resampled. The measurement
    // was circular, and so was the conclusion drawn from it. Re-measuring at
    // 3.902x against a Lanczos upscale reproduced the same false result for the
    // same reason: an upscale is derived from the bitmap too.
    //
    // The only non-circular instrument here is `bench:scale` against real vector
    // originals, where the truth is a shape the tracer never saw. It says
    // refinement is worth +3.01 dB on 300 real logos, and the current default
    // holds 17.26 dB with 2,549 curves at 100% detail on corpus/src.
    //
    // A tracer's job is to recover a resolution-independent shape. Callers who
    // want the input reproduced have `pixel`, `embed` and `lossless`, all of
    // which are bit-exact and none of which guess.
    notes.push('Auto-tuned trace for photographic content: 48-colour palette with gradient de-banding.');
    return { colors: 48, gradients: true, ...refine };
  }

  if (flat.distinctColors > FLAT_COLOR_COUNT) {
    notes.push(`Auto-tuned trace for rich colour (${flat.distinctColors} colours): 32-colour palette.`);
    return { colors: 32, ...refine };
  }
  return { ...refine };
}

async function runTrace(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const preset = opts.preset && opts.preset !== 'auto' && opts.preset in PRESETS
    ? PRESETS[opts.preset as keyof typeof PRESETS]
    : autoTracePreset(input.image, notes);

  const base: TraceOptions = {
    ...TRACE_DEFAULTS,
    // Ahead of the spreads so a caller can still pass its own, or null to opt
    // out. Without it an oversized image ends the process with a V8 heap dump
    // instead of a sentence naming three ways forward.
    loopBudget: heapLoopBudget(),
    ...preset,
    ...stripUndefined(opts.trace ?? {}),
    generator,
    title: opts.title,
  };

  const targetSsim = opts.targetSsim;
  const targetPsnr = opts.targetPsnr;
  const hasTarget = targetSsim !== undefined || targetPsnr !== undefined;
  const maxColors = Math.min(256, opts.maxColors ?? 256);
  const maxSteps = opts.maxRefineSteps ?? 6;

  // A size budget is the inverse search — relax until it fits — so it runs its
  // own loop. Asking to grow quality *and* shrink the file at once is
  // contradictory; the budget is the binding constraint and says what it cost.
  if (opts.maxBytes !== undefined || opts.maxNodes !== undefined) {
    if (hasTarget) {
      notes.push('A size budget and a quality target were both given; the budget binds, and the accuracy it cost is reported.');
    }
    // Each step is a trace but only the baseline and the settled result are
    // rendered, so eight measure-only steps are cheap. A direct bisection needs
    // about six to converge; four (the old default, tuned for the old expand-
    // then-bisect) left a 200 KB target overshooting to 127 KB.
    return runBudget(input, base, opts, notes, opts.maxRefineSteps ?? 8);
  }

  let current: TraceOptions = { ...base };
  let best: { out: ReturnType<typeof trace>; report?: QualityReport; opts: TraceOptions } | null = null;
  let steps = 0;

  for (;;) {
    steps++;
    const out = trace(input.image, current);

    if (!hasTarget) {
      return traceResult(input, out, current, notes, undefined);
    }

    const report = await verifySvg(out.svg, input.image, opts.compare);
    const better = !best?.report || report.ssim > best.report.ssim;
    if (better) best = { out, report, opts: current };

    const ssimOk = targetSsim === undefined || report.ssim >= targetSsim;
    const psnrOk = targetPsnr === undefined || report.psnr >= targetPsnr;
    if (ssimOk && psnrOk) {
      notes.push(`Reached target in ${steps} step${steps === 1 ? '' : 's'}.`);
      return traceResult(input, out, current, notes, report);
    }

    const next = escalate(current, maxColors);
    if (!next || steps >= maxSteps) {
      notes.push(
        `Stopped after ${steps} step${steps === 1 ? '' : 's'} without reaching the target ` +
          `(best mean SSIM ${best!.report!.ssim.toFixed(4)}). Tracing cannot represent every ` +
          `image exactly — use --mode embed if the target is non-negotiable.`,
      );
      return traceResult(input, best!.out, best!.opts, notes, best!.report);
    }
    current = next;
  }
}

/**
 * Trace under a size/complexity budget, and report what it cost.
 *
 * The mirror of the quality-target loop: instead of escalating until accuracy
 * is high enough, this relaxes until the file is small enough — then renders
 * both the unconstrained and the final result so the caller is told, in SSIM,
 * exactly what the smaller file bought. A budget without that receipt would be
 * the opaque simplification slider every other tracer already ships.
 *
 * Intermediate steps are measured on bytes/nodes alone (cheap, no render); only
 * the baseline and the settled result are rendered.
 */
async function runBudget(
  input: VectorizeInput,
  base: TraceOptions,
  opts: VectorizeOptions,
  notes: string[],
  maxSteps: number,
): Promise<VectorizeResult> {
  const targetBytes = opts.maxBytes;
  const targetNodes = opts.maxNodes;
  const fits = (c: SvgComplexity): boolean =>
    (targetBytes === undefined || c.bytes <= targetBytes) &&
    (targetNodes === undefined || c.nodes <= targetNodes);

  const baseOut = trace(input.image, base);
  const baseline = measureSvgComplexity(baseOut.svg);
  const baselineReport = await verifySvg(baseOut.svg, input.image, opts.compare);

  let current: TraceOptions = { ...base };
  let out = baseOut;
  let complexity = baseline;
  let steps = 0;

  if (!fits(baseline)) {
    // Relaxation is a single continuous strength `t`, and `relaxBy` is now
    // monotone and cliff-free in it (see there), so the search is a plain
    // bisection: find the *least* relaxation that still meets the budget, which
    // is the most accurate result that fits.
    //
    // The old version expanded through a fixed ladder [0.25, 0.5, 0.75, 1] and
    // only then bisected. On a four-step budget the ladder ate most of the
    // steps and the bisection never converged — a 200 KB target settled at
    // 127 KB, a 40% overshoot, because the search ran out of moves before it
    // could tighten. A direct bisection spends every step narrowing the bracket.
    let lo = 0;          // known not to fit (the baseline is over budget)
    let hi = -1;         // smallest t known to fit
    let hiOut: ReturnType<typeof trace> | null = null;
    let hiOpts: TraceOptions | null = null;
    let hiComplexity: SvgComplexity | null = null;

    const attempt = (t: number): boolean => {
      const o = relaxBy(base, t);
      const r = trace(input.image, o);
      const c = measureSvgComplexity(r.svg);
      steps++;
      if (fits(c)) {
        if (hi < 0 || t < hi) { hi = t; hiOut = r; hiOpts = o; hiComplexity = c; }
        return true;
      }
      lo = Math.max(lo, t);
      return false;
    };

    // Maximum relaxation first: if even that does not fit, the budget is below
    // what these levers can reach and there is no point bisecting.
    attempt(1);

    // Bisect the [lo, hi] bracket — lo fails, hi fits — for the tightest fit the
    // step budget allows. A floor of 0.02 in `t` is finer than the byte
    // granularity of any single trace, so stopping there costs nothing real.
    while (hi > 0 && steps < maxSteps && hi - lo > 0.02) {
      attempt((lo + hi) / 2);
    }

    if (hiOut) {
      out = hiOut;
      current = hiOpts!;
      complexity = hiComplexity!;
    } else {
      // Nothing fit; return the smallest we produced rather than the baseline.
      current = relaxBy(base, 1);
      out = trace(input.image, current);
      complexity = measureSvgComplexity(out.svg);
    }
  }

  const met = fits(complexity);
  // Re-render only if we actually moved, so an already-fitting image pays once.
  const report = steps === 0
    ? baselineReport
    : await verifySvg(out.svg, input.image, opts.compare);

  const budget: SizeBudgetReport = {
    targetBytes, targetNodes,
    bytes: complexity.bytes, nodes: complexity.nodes,
    met, steps,
    baselineBytes: baseline.bytes, baselineNodes: baseline.nodes,
    baselineSsim: baselineReport.ssim,
    ssim: report.ssim,
    ssimCost: report.ssim - baselineReport.ssim,
  };

  notes.push(
    met
      ? `Met the budget in ${steps} step${steps === 1 ? '' : 's'}: ` +
        `${baseline.bytes}→${complexity.bytes} bytes, ${baseline.nodes}→${complexity.nodes} nodes, ` +
        `for ${(budget.ssimCost ?? 0) >= 0 ? 'no' : `${Math.abs(budget.ssimCost!).toFixed(4)}`} SSIM.`
      : `Could not reach the budget after ${steps} step${steps === 1 ? '' : 's'} — ` +
        `smallest was ${complexity.bytes} bytes / ${complexity.nodes} nodes. ` +
        'Relaxing further would discard structure, so the closest result is returned.',
  );

  const result = traceResult(input, out, current, notes, report);
  result.budget = budget;
  return result;
}

/**
 * Relaxation as a single continuous strength — the inverse of {@link escalate},
 * but parameterised so the budget search can bisect it.
 *
 * `t = 0` is the caller's settings untouched; `t = 1` is as coarse as this will
 * go. All three levers move together because they remove different things:
 * loosening the fit drops anchor points along a curve, absorbing specks drops
 * whole tiny regions, and trimming the palette merges regions outright.
 */
function relaxBy(base: TraceOptions, t: number): TraceOptions {
  const k = 1 + t * 7; // fit tolerance grows up to 8×
  // The levers are *staged*, not fired together, because they cost different
  // things and — this is the part an earlier version got wrong — because a
  // structural lever is *discontinuous*. Dropping specks or palette entries
  // collapses the file in one jump: on a photograph, `minArea` reaching ~20
  // took the byte count from 319 KB straight to 62 KB, a 5× cliff with nothing
  // in between. A budget that landed in that gap could not be hit at all — the
  // bisection would settle on 62 KB for a 120 KB target and pay accuracy it
  // never needed.
  //
  // So the two cheap, *continuous* levers run first and do as much as they can
  // before any structural one engages:
  //
  //   1. Curve-fit tolerance — spends sub-pixel precision along a curve.
  //   2. Coordinate precision — rounds path coordinates, shrinking bytes
  //      smoothly (each dropped decimal is ~15–25% fewer bytes) while deleting
  //      no structure at all. This is what fills the cliff.
  //
  // Only once those are exhausted do the structural levers start:
  //
  //   3. Speckle — absorbs whole small regions.
  //   4. Palette — merges regions by trimming colours.
  const basePrec = base.precision ?? 2;
  // Precision falls from its base toward 0 across the middle of the range, so it
  // is carrying the load exactly where the old curve fell off a cliff.
  const precDrop = Math.max(0, Math.min(1, (t - 0.2) / 0.35));
  const precision = Math.max(0, Math.round(basePrec - precDrop * basePrec));
  const speckle = Math.max(0, (t - 0.55) / 0.45); // idle until t = 0.55 (was 0.4)
  const palette = Math.max(0, (t - 0.75) / 0.25); // idle until t = 0.75 (was 0.6)
  return {
    ...base,
    tolerance: Math.min(8, (base.tolerance ?? 0.4) * k),
    fitError: Math.min(8, (base.fitError ?? 0.4) * k),
    precision,
    minArea: Math.round((base.minArea ?? 0) + speckle * 64),
    colors: Math.max(2, Math.round((base.colors ?? 16) * (1 - 0.6 * palette))),
  };
}

/** Return the next, more aggressive parameter set, or null when maxed out. */
function escalate(o: TraceOptions, maxColors: number): TraceOptions | null {
  const colors = Math.min(maxColors, Math.round((o.colors ?? 16) * 2));
  const tolerance = Math.max(0.05, (o.tolerance ?? 1) * 0.6);
  const fitError = Math.max(0.05, (o.fitError ?? 1) * 0.6);
  const minArea = Math.max(0, Math.floor((o.minArea ?? 0) / 2));

  const exhausted =
    colors === o.colors && tolerance === o.tolerance &&
    fitError === o.fitError && minArea === o.minArea;
  if (exhausted) return null;

  return { ...o, colors, tolerance, fitError, minArea };
}

function traceResult(
  input: VectorizeInput,
  out: ReturnType<typeof trace>,
  settled: TraceOptions,
  notes: string[],
  report: QualityReport | undefined,
): VectorizeResult {
  if (out.despeckled > 0) {
    notes.push(`Absorbed ${out.despeckled} speck${out.despeckled === 1 ? '' : 's'} below --min-area.`);
  }
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'trace',
    shapes: out.shapes,
    colors: out.colors,
    lossless: report?.lossless ?? false,
    quality: report,
    notes,
    elapsedMs: 0,
    settled: {
      colors: settled.colors ?? TRACE_DEFAULTS.colors,
      tolerance: settled.tolerance ?? TRACE_DEFAULTS.tolerance,
      fitError: settled.fitError ?? TRACE_DEFAULTS.fitError,
      cornerAngle: settled.cornerAngle ?? TRACE_DEFAULTS.cornerAngle,
      minArea: settled.minArea ?? TRACE_DEFAULTS.minArea,
      regions: out.regions,
    },
  };
}

// ---------------------------------------------------------------------------
// SVG -> raster
// ---------------------------------------------------------------------------

export interface RasterizeToBufferOptions extends RasterizeOptions {
  encode: EncodeOptions;
}

export interface RasterizeOutcome {
  buffer: Buffer;
  width: number;
  height: number;
  intrinsic: { width: number; height: number };
  inlined: string[];
  /** Present when `verify` was requested: the encoded file re-read and compared. */
  quality?: QualityReport;
}

/**
 * Render an SVG and encode it.
 *
 * When `verify` is set, the *encoded* bytes are decoded again and compared
 * against the render. That catches the failure people actually hit — asking for
 * a JPEG and silently losing the alpha channel, or a lossy WebP quality setting
 * doing more damage than expected.
 */
export async function rasterize(
  svg: string | Uint8Array,
  opts: RasterizeToBufferOptions,
  verify = false,
): Promise<RasterizeOutcome> {
  const { image, intrinsic, inlined } = await rasterizeSvg(svg, opts);
  const buffer = await encodeRaster(image, opts.encode);

  const outcome: RasterizeOutcome = {
    buffer,
    width: image.width,
    height: image.height,
    intrinsic,
    inlined,
  };

  if (verify) {
    const roundTrip = await decodeRaster(buffer, { applyOrientation: false });
    outcome.quality = compareImages(image, roundTrip.image);
  }

  return outcome;
}

/** Read either a raster or an SVG and produce comparable RGBA pixels. */
export async function loadAnyAsRaster(
  bytes: Uint8Array,
  path: string | undefined,
  rasterizeOpts?: RasterizeOptions,
): Promise<{ image: RasterImage; kind: 'raster' | 'svg'; meta?: SourceMeta }> {
  if (looksLikeSvg(bytes)) {
    const { image } = await rasterizeSvg(bytes, rasterizeOpts);
    return { image, kind: 'svg' };
  }
  const { image, meta } = await decodeRaster(bytes);
  return { image, kind: 'raster', meta };
}

export function suggestTitle(path: string): string {
  return basename(path).replace(/\.[^.]+$/, '');
}

function stripUndefined<T extends object>(obj: T): Partial<T> {
  const out: Partial<T> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined) (out as Record<string, unknown>)[k] = v;
  }
  return out;
}

/**
 * Group digits the same way everywhere.
 *
 * `toLocaleString()` follows the machine's locale, so the same build prints
 * "236,034" on one developer's box and "2,36,034" on another's. Diagnostic
 * output should not depend on where it runs.
 */
function formatCount(n: number): string {
  return n.toLocaleString('en-US');
}
