import { basename } from 'node:path';
import { decodeRaster, looksLikeSvg, type DecodeOptions } from './io/decode.js';
import { encodeRaster, type EncodeOptions } from './io/encode.js';
import { rasterizeSvg, type RasterizeOptions } from './io/rasterize.js';
import { packRgba } from './image.js';
import { compareImages, type CompareOptions } from './metrics/index.js';
import type {
  QualityReport, RasterImage, SourceMeta, VectorizeMode, VectorizeResult,
} from './types.js';
import { vectorizeEmbed, type EmbedOptions } from './vectorize/embed.js';
import { vectorizeExact, type ExactOptions } from './vectorize/exact.js';
import { vectorizePixels, type PixelVectorizeOptions } from './vectorize/pixel.js';
import { trace, TRACE_DEFAULTS, type TraceOptions } from './vectorize/trace.js';

export const VERSION = '1.30.0';

const GENERATOR = `Generated by pixvec v${VERSION}`;

export type VectorizeModeOption = VectorizeMode | 'auto' | 'lossless';

export type Preset = 'auto' | 'logo' | 'lineart' | 'poster' | 'photo' | 'detailed' | 'pixelart' | 'exact';

/**
 * Presets are starting points, not straitjackets — every field stays
 * overridable. They exist because the useful parameter combinations cluster by
 * *what kind of picture it is*, and asking someone to guess a Douglas–Peucker
 * tolerance is a bad interface.
 */
export const PRESETS: Record<Exclude<Preset, 'auto' | 'pixelart' | 'exact'>, TraceOptions> = {
  // Tolerances retuned after the curve-fit diagnosis. `logo` and `lineart` keep
  // a higher value (0.6) because there a large arc should stay a few smooth,
  // editable Béziers rather than a fine polygon — that is the whole point of a
  // logo tracer. `poster`, `photo` and `detailed` favour accuracy, where the
  // measured win is largest; `photo` at the old 1.4 was the worst setting in the
  // whole table.
  logo: { colors: 16, minArea: 8, tolerance: 0.6, fitError: 0.6, cornerAngle: 75 },
  lineart: { colors: 6, minArea: 4, tolerance: 0.6, fitError: 0.6, cornerAngle: 60 },
  poster: { colors: 32, minArea: 12, tolerance: 0.5, fitError: 0.5, cornerAngle: 80 },
  photo: { colors: 64, minArea: 16, tolerance: 0.4, fitError: 0.4, cornerAngle: 90 },
  detailed: { colors: 48, minArea: 2, tolerance: 0.3, fitError: 0.3, cornerAngle: 60 },
};

export interface VectorizeOptions {
  /**
   * `auto` inspects the image and picks. `lossless` guarantees a bit-exact
   * result, preferring real geometry (`pixel`) and falling back to `embed`.
   */
  mode?: VectorizeModeOption;
  preset?: Preset;
  /** Render the result and measure it against the input. */
  verify?: boolean;
  /** Escalate trace settings until mean SSIM reaches this. Implies `verify`. */
  targetSsim?: number;
  /** Escalate trace settings until PSNR reaches this many dB. Implies `verify`. */
  targetPsnr?: number;
  /** Upper bound on palette size during refinement. */
  maxColors?: number;
  /** Refinement attempts before giving up and returning the best so far. */
  maxRefineSteps?: number;
  /**
   * What `lossless` optimises for once exactness is assured.
   *
   * `auto` (default) keeps real editable geometry whenever it is not
   * unreasonably larger than the alternative — see {@link maxGeometryRatio}.
   * `geometry` insists on real paths at any size. `size` always takes the
   * smallest exact result, which on photographs is the embedded bitmap.
   */
  losslessPrefer?: 'auto' | 'geometry' | 'size';
  /**
   * Under `auto`, how many times larger real geometry may be than the smallest
   * exact alternative before it stops being worth it. Default 4.
   */
  maxGeometryRatio?: number;
  trace?: TraceOptions;
  embed?: EmbedOptions;
  pixel?: PixelVectorizeOptions;
  exact?: ExactOptions;
  compare?: CompareOptions;
  /** `<title>` for the generated document. */
  title?: string;
  /** Suppress the generator comment. */
  noGenerator?: boolean;
}

export interface VectorizeInput {
  image: RasterImage;
  meta: SourceMeta;
  bytes: Uint8Array;
}

/** Read and normalise a raster file. */
export async function loadRaster(
  path: string | Uint8Array,
  opts?: DecodeOptions,
): Promise<VectorizeInput> {
  const { image, meta, bytes } = await decodeRaster(path, opts);
  return { image, meta, bytes };
}

/**
 * Convert a raster image to SVG.
 *
 * The returned `quality` field, when verification runs, is measured against the
 * actual rendered output — not estimated from the parameters. If it says the
 * result is lossless, the file was rendered and compared pixel by pixel.
 */
export async function vectorize(
  input: VectorizeInput,
  opts: VectorizeOptions = {},
): Promise<VectorizeResult> {
  const started = Date.now();
  const notes: string[] = [];
  const generator = opts.noGenerator ? undefined : GENERATOR;
  const wantsTarget = opts.targetSsim !== undefined || opts.targetPsnr !== undefined;
  const verify = opts.verify || wantsTarget;

  // Strict lossless is its own path: it verifies every candidate by rendering
  // and refuses to return anything that is not bit-exact.
  if (opts.mode === 'lossless' || opts.preset === 'exact') {
    const strict = await runLossless(input, opts, generator, notes);
    strict.elapsedMs = Date.now() - started;
    strict.notes = notes;
    return strict;
  }

  const mode = resolveMode(input, opts, notes);

  let result: VectorizeResult;
  switch (mode) {
    case 'embed':
      result = await runEmbed(input, opts, generator, notes);
      break;
    case 'pixel':
      result = runPixel(input, opts, generator, notes);
      break;
    case 'trace':
      result = await runTrace(input, opts, generator, notes);
      break;
  }

  if (verify && !result.quality) {
    result.quality = await verifySvg(result.svg, input.image, opts.compare);
  }

  // Auto mode picked a strategy from image statistics before seeing the result.
  // If that guess produced something an exact alternative beats on *both* size
  // and accuracy, take the alternative — there is no trade-off to weigh.
  if ((opts.mode ?? 'auto') === 'auto' && result.mode === 'trace') {
    const better = await findDominatingExact(input, result, opts, notes);
    if (better) result = better;
  }

  if (verify && !result.quality) {
    result.quality = await verifySvg(result.svg, input.image, opts.compare);
  }

  // Measurement outranks assertion. A mode can be lossless by construction and
  // still not round-trip through a particular renderer — an embedded JPEG is the
  // usual case, where the payload survives intact but the renderer's decoder
  // rounds differently. Reporting the construction-time claim when a measurement
  // contradicts it would be the one lie this tool must not tell.
  if (result.quality) {
    if (!result.quality.lossless && result.lossless) {
      notes.push(
        `Verification found ${result.quality.pixels - result.quality.exactPixels} ` +
          `differing pixel(s) (max ${result.quality.maxChannelDiff}/255). The mode is ` +
          `exact by construction, so this is the renderer's decoder, not lost data.`,
      );
    }
    result.lossless = result.quality.lossless;
  }

  result.elapsedMs = Date.now() - started;
  result.notes = notes;
  return result;
}

/** Render an SVG at the reference image's exact size and compare the two. */
export async function verifySvg(
  svg: string,
  reference: RasterImage,
  compare?: CompareOptions,
  rasterizeOpts?: RasterizeOptions,
): Promise<QualityReport> {
  let rendered = await rasterizeSvg(svg, { ...rasterizeOpts });
  if (rendered.image.width !== reference.width || rendered.image.height !== reference.height) {
    // Force the exact reference size; an off-by-one from unit resolution would
    // otherwise make the comparison impossible rather than merely imprecise.
    rendered = await rasterizeSvg(svg, { ...rasterizeOpts, width: reference.width });
  }
  return compareImages(reference, rendered.image, compare);
}

// ---------------------------------------------------------------------------
// Mode selection
// ---------------------------------------------------------------------------

interface Flatness {
  distinctColors: number;
  capped: boolean;
  /** Horizontal runs per pixel. Near 0 is flat artwork, near 1 is noise. */
  runRatio: number;
}

/**
 * Two cheap signals separate "artwork" from "photograph" reliably:
 * the number of distinct colours, and how often colour changes along a scanline.
 * A screenshot can have thousands of colours yet still be mostly flat; a
 * gradient-heavy photo has both high counts and high run density.
 */
export function measureFlatness(img: RasterImage, colorCap = 4096): Flatness {
  const seen = new Set<number>();
  const d = img.data;
  let runs = 0;
  let capped = false;
  let prev = -1;

  for (let y = 0; y < img.height; y++) {
    prev = -1;
    for (let x = 0; x < img.width; x++) {
      const o = (y * img.width + x) * 4;
      const a = d[o + 3];
      const key = a === 0 ? 0 : packRgba(d[o], d[o + 1], d[o + 2], a);
      if (key !== prev) { runs++; prev = key; }
      if (!capped) {
        seen.add(key);
        if (seen.size > colorCap) capped = true;
      }
    }
  }

  return {
    distinctColors: seen.size,
    capped,
    runRatio: runs / (img.width * img.height),
  };
}

function resolveMode(
  input: VectorizeInput,
  opts: VectorizeOptions,
  notes: string[],
): VectorizeMode {
  if (opts.preset === 'pixelart') return 'pixel';
  // `lossless` and the `exact` preset never reach here — `vectorize` routes them
  // to `runLossless`, which decides by measuring candidates rather than guessing.
  if (opts.mode && opts.mode !== 'auto' && opts.mode !== 'lossless') return opts.mode;

  const flat = measureFlatness(input.image, 4096);
  if (isPixelFeasible(input.image, flat)) {
    notes.push(
      `Auto-selected pixel mode: ${flat.distinctColors} distinct colours, ` +
        `${(flat.runRatio * 100).toFixed(1)}% run density. Output is bit-exact.`,
    );
    return 'pixel';
  }

  notes.push(
    `Auto-selected trace mode: ${flat.capped ? '>4096' : flat.distinctColors} distinct colours, ` +
      `${(flat.runRatio * 100).toFixed(1)}% run density. Tracing approximates; ` +
      `use --mode embed if you need this image reproduced exactly.`,
  );
  return 'trace';
}

/** Ceiling on rectangles before a pixel-mode file stops being worth having. */
const PIXEL_RECT_BUDGET = 600_000;
/** Run density below which greedy meshing still folds many pixels per rectangle. */
const FLAT_RUN_RATIO = 0.12;
/** Palette size below which an image is flat artwork whatever its run density. */
const FLAT_COLOR_COUNT = 64;

/**
 * Decide whether pixel mode would produce a file worth having.
 *
 * Two independent signals each indicate genuinely flat content, and either one
 * is enough:
 *
 * - **Long colour runs.** Greedy meshing folds an order of magnitude of pixels
 *   into each rectangle, so the output is real geometry rather than a bitmap
 *   spelled out in `<rect>` elements.
 * - **A small palette.** A 32×32 sprite changes colour every few pixels, so its
 *   run density looks photographic — but four colours across a thousand pixels
 *   is unmistakably artwork, and pixel mode handles it perfectly.
 *
 * Requiring both would push sprites to the tracer, which is exactly wrong: pixel
 * art is the one case where exact output is both achievable and expected.
 * A hard rectangle budget then bounds the cost regardless of which signal fired.
 */
function isPixelFeasible(img: RasterImage, flat: Flatness): boolean {
  if (flat.capped || flat.distinctColors > 4096) return false;

  const estimatedRects = flat.runRatio * img.width * img.height;
  if (estimatedRects > PIXEL_RECT_BUDGET) return false;

  return flat.runRatio <= FLAT_RUN_RATIO || flat.distinctColors <= FLAT_COLOR_COUNT;
}

/**
 * Look for an exact result that beats an approximate one outright.
 *
 * Auto mode chooses from colour count and run density, before anything has been
 * produced. Those signals misjudge anti-aliased artwork badly: a logo with 194
 * colours and soft edges reads as "too varied for exact geometry", goes to the
 * tracer, and comes back **eight times larger than the source file and still
 * approximate** — while an embedded copy would have been smaller *and* exact.
 *
 * A user cannot be expected to notice that, so this checks. It only runs when
 * the traced output is already suspiciously large (bigger than the input file),
 * which keeps the extra work off the common path where tracing did its job.
 *
 * The bar is deliberately dominance, not preference: the alternative must be
 * both smaller and bit-exact. Anything less is a genuine trade-off, and those
 * belong to the caller.
 */
async function findDominatingExact(
  input: VectorizeInput,
  traced: VectorizeResult,
  opts: VectorizeOptions,
  notes: string[],
): Promise<VectorizeResult | null> {
  const tracedBytes = Buffer.byteLength(traced.svg);
  if (tracedBytes <= input.meta.bytes) return null;

  try {
    // `preserve` first because it is smaller and keeps the original file, then
    // `png` which always renders exactly. Asking for `auto` here would be a
    // trap: on a JPEG source it picks the preserved payload, which is smaller
    // but *not* bit-exact through the renderer, so the check would find no
    // dominating candidate and silently keep the worse traced result.
    let exact: Awaited<ReturnType<typeof vectorizeEmbed>> | null = null;
    let exactBytes = 0;
    let report: QualityReport | null = null;

    for (const strategy of ['preserve', 'png'] as const) {
      const candidate = await vectorizeEmbed(input.image, input.bytes, input.meta, {
        ...opts.embed, strategy,
        generator: opts.noGenerator ? undefined : GENERATOR,
        title: opts.title,
      });
      const bytes = Buffer.byteLength(candidate.svg);
      if (bytes >= tracedBytes) continue;

      const measured = await verifySvg(candidate.svg, input.image, opts.compare);
      if (!measured.lossless) continue;

      exact = candidate;
      exactBytes = bytes;
      report = measured;
      break;
    }

    if (!exact || !report) return null;

    notes.push(
      `Switched to embed: tracing produced ${formatCount(tracedBytes)} bytes at ` +
        `SSIM ${(traced.quality?.ssim ?? 0).toFixed(4)}, while an exact copy is ` +
        `${formatCount(exactBytes)} bytes. Smaller and bit-exact, so there was ` +
        `nothing to trade. Use --mode trace to force real curves.`,
    );

    return {
      svg: exact.svg,
      width: input.image.width,
      height: input.image.height,
      mode: 'embed',
      shapes: 1,
      colors: 0,
      lossless: true,
      quality: report,
      notes,
      elapsedMs: 0,
      settled: {
        mime: exact.mime,
        payloadBytes: exact.payloadBytes,
        bytesPreserved: exact.bytesPreserved,
        rejectedTraceBytes: tracedBytes,
      },
    };
  } catch {
    // The comparison is an optimisation; failing it just keeps the traced result.
    return null;
  }
}

// ---------------------------------------------------------------------------
// Strict lossless
// ---------------------------------------------------------------------------

interface LosslessCandidate {
  svg: string;
  mode: VectorizeMode;
  shapes: number;
  colors: number;
  /** Short description used in notes and errors. */
  label: string;
  settled?: Record<string, number | string | boolean>;
  report?: QualityReport;
}

/**
 * Produce a bit-exact SVG, or fail loudly.
 *
 * The guarantee is enforced by measurement, not by construction: every
 * candidate is rendered back to pixels and compared against the source, and
 * anything that is not bit-identical is discarded. If nothing survives, this
 * throws rather than returning a near-miss — silently downgrading a lossless
 * request is the one failure mode that would make the promise worthless.
 *
 * Candidates are tried in order of how useful the result is:
 *
 * 1. **Exact geometry** — real editable paths, either rectangles or contours,
 *    whichever encodes smaller.
 * 2. **Embed, original bytes preserved** — gives a byte-identical round trip of
 *    the source *file*, not merely of its pixels.
 * 3. **Embed, re-encoded as PNG** — always renders exactly, at the cost of no
 *    longer carrying the original file.
 *
 * Step 2 sits above step 3 because it is strictly better when it works, and it
 * usually does; it fails for JPEG sources, where the renderer's decoder rounds
 * its inverse DCT differently from the reference decoder.
 */
async function runLossless(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const prefer = opts.losslessPrefer ?? 'auto';
  const maxRatio = opts.maxGeometryRatio ?? 4;
  const title = opts.title;
  const candidates: LosslessCandidate[] = [];

  // --- 1. Real geometry ---
  try {
    const exact = vectorizeExact(input.image, {
      ...opts.pixel, ...opts.exact, generator, title,
    });
    candidates.push({
      svg: exact.svg,
      mode: 'pixel',
      shapes: exact.shapes,
      colors: exact.colors,
      label: `exact geometry (${exact.strategy})`,
      settled: {
        strategy: exact.strategy,
        rectangleBytes: exact.sizes.rectangles,
        ...(exact.sizes.contours !== undefined ? { contourBytes: exact.sizes.contours } : {}),
      },
    });
  } catch (err) {
    notes.push(`Exact geometry unavailable: ${(err as Error).message}`);
  }

  // --- 2 & 3. Embedded payloads ---
  const requested = opts.embed?.strategy;
  const strategies: Array<EmbedOptions['strategy']> =
    requested && requested !== 'auto' ? [requested] : ['preserve', 'png'];

  for (const strategy of strategies) {
    try {
      const out = await vectorizeEmbed(input.image, input.bytes, input.meta, {
        ...opts.embed, strategy, generator, title,
      });
      candidates.push({
        svg: out.svg,
        mode: 'embed',
        shapes: 1,
        colors: 0,
        label: `embed (${out.bytesPreserved ? 'original bytes preserved' : out.mime})`,
        settled: {
          mime: out.mime,
          payloadBytes: out.payloadBytes,
          bytesPreserved: out.bytesPreserved,
        },
      });
    } catch (err) {
      notes.push(`Embed strategy "${strategy}" failed: ${(err as Error).message}`);
    }
  }

  // Two strategies can converge on the same output — a BMP source has no
  // preservable payload, so both `preserve` and `png` re-encode identically.
  // Verifying and reporting it twice is just noise.
  const unique: LosslessCandidate[] = [];
  for (const candidate of candidates) {
    if (!unique.some((seen) => seen.svg === candidate.svg)) unique.push(candidate);
  }

  // --- Verify every candidate; keep only the provably exact ones. ---
  const exactOnes: LosslessCandidate[] = [];
  const rejected: string[] = [];

  for (const candidate of unique) {
    const report = await verifySvg(candidate.svg, input.image, opts.compare);
    candidate.report = report;
    if (report.lossless) exactOnes.push(candidate);
    else {
      rejected.push(
        `${candidate.label}: ${report.pixels - report.exactPixels} pixel(s) differ ` +
          `(max ${report.maxChannelDiff}/255)`,
      );
    }
  }

  if (exactOnes.length === 0) {
    throw new Error(
      `Could not produce a bit-exact SVG for this input. Tried:\n` +
        rejected.map((r) => `  - ${r}`).join('\n') +
        `\nThis should not happen; please report it with the input image.`,
    );
  }

  // --- Choose among the survivors. ---
  const geometry = exactOnes.find((c) => c.mode === 'pixel');
  const smallest = [...exactOnes].sort((a, b) => a.svg.length - b.svg.length)[0];

  let chosen: LosslessCandidate;
  let rationale: string | null = null;

  if (prefer === 'size' || !geometry) {
    chosen = smallest;
  } else if (prefer === 'geometry') {
    chosen = geometry;
  } else {
    // `auto`: real geometry is worth a premium, but not an unbounded one. A
    // photograph encodes exactly as roughly one rectangle per pixel, which is a
    // multi-megabyte file that is vector in name only.
    const ratio = geometry.svg.length / smallest.svg.length;
    if (ratio <= maxRatio) {
      chosen = geometry;
    } else {
      chosen = smallest;
      rationale =
        `Exact geometry would be ${ratio.toFixed(1)}x larger than the embedded bitmap ` +
        `(${formatCount(geometry.svg.length)} vs ${formatCount(smallest.svg.length)} bytes), ` +
        `so the bitmap was used. Both are bit-exact; pass --prefer geometry to force real paths.`;
    }
  }

  if (rejected.length > 0) {
    notes.push(`Rejected ${rejected.length} candidate(s) that were not bit-exact: ${rejected.join('; ')}.`);
  }
  for (const c of exactOnes) {
    if (c !== chosen) notes.push(`Alternative: ${c.label}, ${formatCount(c.svg.length)} bytes.`);
  }
  notes.push(`Verified bit-exact by rendering and comparing every pixel — ${chosen.label}.`);
  if (rationale) notes.push(rationale);
  else if (geometry && chosen === geometry && smallest !== geometry) {
    notes.push('Kept real geometry over the smaller embedded bitmap; pass --prefer size to invert that.');
  }

  return {
    svg: chosen.svg,
    width: input.image.width,
    height: input.image.height,
    mode: chosen.mode,
    shapes: chosen.shapes,
    colors: chosen.colors,
    lossless: true,
    quality: chosen.report,
    notes,
    elapsedMs: 0,
    settled: chosen.settled,
  };
}

// ---------------------------------------------------------------------------
// Per-mode runners
// ---------------------------------------------------------------------------

async function runEmbed(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const out = await vectorizeEmbed(input.image, input.bytes, input.meta, {
    ...opts.embed,
    generator,
    title: opts.title,
  });
  notes.push(...out.notes);
  if (out.bytesPreserved) {
    notes.push('Original file bytes preserved verbatim inside the SVG.');
  }
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'embed',
    shapes: 1,
    colors: 0,
    lossless: true,
    notes,
    elapsedMs: 0,
    settled: { mime: out.mime, payloadBytes: out.payloadBytes, bytesPreserved: out.bytesPreserved },
  };
}

function runPixel(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): VectorizeResult {
  const out = vectorizePixels(input.image, { ...opts.pixel, generator, title: opts.title });
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'pixel',
    shapes: out.shapes,
    colors: out.colors,
    lossless: true,
    notes,
    elapsedMs: 0,
    settled: { rects: out.rects },
  };
}

/**
 * Trace, then — if a quality target was given — escalate and try again.
 *
 * Each step doubles the palette and tightens the geometric tolerances, because
 * the two failure modes are different: too few colours shows up as banding,
 * too loose a tolerance shows up as rounded-off detail. Moving both keeps the
 * search short. The best result seen is kept, so a target that turns out to be
 * unreachable still returns the closest attempt rather than the last one.
 */
/**
 * When no preset is named, scale the trace settings to the content instead of
 * always using the lean 16-colour default. A photograph traced with 16 colours
 * bands visibly; a zero-config `convert photo.png out.svg` should give it a
 * photo-grade palette and gradient de-banding (which can only help). Flat artwork
 * keeps the lean default, which is already ideal — and is never sent here anyway,
 * since auto mode routes it to bit-exact pixel output first.
 */
function autoTracePreset(img: RasterImage, notes: string[]): TraceOptions {
  const flat = measureFlatness(img, 4096);
  // Only the palette is widened (plus gradient de-banding for photos). minArea
  // and the fit tolerances are deliberately left to auto-scale: forcing a larger
  // minArea here despeckled fine detail — feathers, foliage — and cost more
  // accuracy than the extra colours bought back.
  if (flat.capped) {
    notes.push('Auto-tuned trace for photographic content: 48-colour palette with gradient de-banding.');
    return { colors: 48, gradients: true };
  }
  if (flat.distinctColors > FLAT_COLOR_COUNT) {
    notes.push(`Auto-tuned trace for rich colour (${flat.distinctColors} colours): 32-colour palette.`);
    return { colors: 32 };
  }
  return {};
}

async function runTrace(
  input: VectorizeInput,
  opts: VectorizeOptions,
  generator: string | undefined,
  notes: string[],
): Promise<VectorizeResult> {
  const preset = opts.preset && opts.preset !== 'auto' && opts.preset in PRESETS
    ? PRESETS[opts.preset as keyof typeof PRESETS]
    : autoTracePreset(input.image, notes);

  const base: TraceOptions = {
    ...TRACE_DEFAULTS,
    ...preset,
    ...stripUndefined(opts.trace ?? {}),
    generator,
    title: opts.title,
  };

  const targetSsim = opts.targetSsim;
  const targetPsnr = opts.targetPsnr;
  const hasTarget = targetSsim !== undefined || targetPsnr !== undefined;
  const maxColors = Math.min(256, opts.maxColors ?? 256);
  const maxSteps = opts.maxRefineSteps ?? 6;

  let current: TraceOptions = { ...base };
  let best: { out: ReturnType<typeof trace>; report?: QualityReport; opts: TraceOptions } | null = null;
  let steps = 0;

  for (;;) {
    steps++;
    const out = trace(input.image, current);

    if (!hasTarget) {
      return traceResult(input, out, current, notes, undefined);
    }

    const report = await verifySvg(out.svg, input.image, opts.compare);
    const better = !best?.report || report.ssim > best.report.ssim;
    if (better) best = { out, report, opts: current };

    const ssimOk = targetSsim === undefined || report.ssim >= targetSsim;
    const psnrOk = targetPsnr === undefined || report.psnr >= targetPsnr;
    if (ssimOk && psnrOk) {
      notes.push(`Reached target in ${steps} step${steps === 1 ? '' : 's'}.`);
      return traceResult(input, out, current, notes, report);
    }

    const next = escalate(current, maxColors);
    if (!next || steps >= maxSteps) {
      notes.push(
        `Stopped after ${steps} step${steps === 1 ? '' : 's'} without reaching the target ` +
          `(best mean SSIM ${best!.report!.ssim.toFixed(4)}). Tracing cannot represent every ` +
          `image exactly — use --mode embed if the target is non-negotiable.`,
      );
      return traceResult(input, best!.out, best!.opts, notes, best!.report);
    }
    current = next;
  }
}

/** Return the next, more aggressive parameter set, or null when maxed out. */
function escalate(o: TraceOptions, maxColors: number): TraceOptions | null {
  const colors = Math.min(maxColors, Math.round((o.colors ?? 16) * 2));
  const tolerance = Math.max(0.05, (o.tolerance ?? 1) * 0.6);
  const fitError = Math.max(0.05, (o.fitError ?? 1) * 0.6);
  const minArea = Math.max(0, Math.floor((o.minArea ?? 0) / 2));

  const exhausted =
    colors === o.colors && tolerance === o.tolerance &&
    fitError === o.fitError && minArea === o.minArea;
  if (exhausted) return null;

  return { ...o, colors, tolerance, fitError, minArea };
}

function traceResult(
  input: VectorizeInput,
  out: ReturnType<typeof trace>,
  settled: TraceOptions,
  notes: string[],
  report: QualityReport | undefined,
): VectorizeResult {
  if (out.despeckled > 0) {
    notes.push(`Absorbed ${out.despeckled} speck${out.despeckled === 1 ? '' : 's'} below --min-area.`);
  }
  return {
    svg: out.svg,
    width: input.image.width,
    height: input.image.height,
    mode: 'trace',
    shapes: out.shapes,
    colors: out.colors,
    lossless: report?.lossless ?? false,
    quality: report,
    notes,
    elapsedMs: 0,
    settled: {
      colors: settled.colors ?? TRACE_DEFAULTS.colors,
      tolerance: settled.tolerance ?? TRACE_DEFAULTS.tolerance,
      fitError: settled.fitError ?? TRACE_DEFAULTS.fitError,
      cornerAngle: settled.cornerAngle ?? TRACE_DEFAULTS.cornerAngle,
      minArea: settled.minArea ?? TRACE_DEFAULTS.minArea,
      regions: out.regions,
    },
  };
}

// ---------------------------------------------------------------------------
// SVG -> raster
// ---------------------------------------------------------------------------

export interface RasterizeToBufferOptions extends RasterizeOptions {
  encode: EncodeOptions;
}

export interface RasterizeOutcome {
  buffer: Buffer;
  width: number;
  height: number;
  intrinsic: { width: number; height: number };
  inlined: string[];
  /** Present when `verify` was requested: the encoded file re-read and compared. */
  quality?: QualityReport;
}

/**
 * Render an SVG and encode it.
 *
 * When `verify` is set, the *encoded* bytes are decoded again and compared
 * against the render. That catches the failure people actually hit — asking for
 * a JPEG and silently losing the alpha channel, or a lossy WebP quality setting
 * doing more damage than expected.
 */
export async function rasterize(
  svg: string | Uint8Array,
  opts: RasterizeToBufferOptions,
  verify = false,
): Promise<RasterizeOutcome> {
  const { image, intrinsic, inlined } = await rasterizeSvg(svg, opts);
  const buffer = await encodeRaster(image, opts.encode);

  const outcome: RasterizeOutcome = {
    buffer,
    width: image.width,
    height: image.height,
    intrinsic,
    inlined,
  };

  if (verify) {
    const roundTrip = await decodeRaster(buffer, { applyOrientation: false });
    outcome.quality = compareImages(image, roundTrip.image);
  }

  return outcome;
}

/** Read either a raster or an SVG and produce comparable RGBA pixels. */
export async function loadAnyAsRaster(
  bytes: Uint8Array,
  path: string | undefined,
  rasterizeOpts?: RasterizeOptions,
): Promise<{ image: RasterImage; kind: 'raster' | 'svg'; meta?: SourceMeta }> {
  if (looksLikeSvg(bytes)) {
    const { image } = await rasterizeSvg(bytes, rasterizeOpts);
    return { image, kind: 'svg' };
  }
  const { image, meta } = await decodeRaster(bytes);
  return { image, kind: 'raster', meta };
}

export function suggestTitle(path: string): string {
  return basename(path).replace(/\.[^.]+$/, '');
}

function stripUndefined<T extends object>(obj: T): Partial<T> {
  const out: Partial<T> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined) (out as Record<string, unknown>)[k] = v;
  }
  return out;
}

/**
 * Group digits the same way everywhere.
 *
 * `toLocaleString()` follows the machine's locale, so the same build prints
 * "236,034" on one developer's box and "2,36,034" on another's. Diagnostic
 * output should not depend on where it runs.
 */
function formatCount(n: number): string {
  return n.toLocaleString('en-US');
}
